const app=document.querySelector('#app'),overlay=document.querySelector('#overlay'),toast=document.querySelector('#toast');
const q=new URLSearchParams(location.search),scheme=q.get('theme')||'fluid';
const projects=[['genethub','开源核心 · 最近'],['genethub-cloud','云端服务 · 昨天'],['design-system','组件库 · 3 天前'],['无项目','普通对话，不访问文件']];
const models=[['GPT-5.2 Codex','OpenAI · 编码 · 视觉 · 400K'],['Claude Opus 4.1','Anthropic · 深度推理 · 200K'],['Gemini 3 Pro','Google · 长上下文 · 1M'],['Qwen3 Coder','本地 · 低延迟 · 128K'],['GPT-5 mini','OpenAI · 快速 · 低成本'],['自动选择','按任务、能力与延迟路由']];
const agents=[['Codex','代码实现 · 图片 · 工具'],['Claude Code','代码推理 · Slash 命令'],['Genet','原生 Agent · 多 Agent'],['OpenCode','开放协议 · 可恢复']];
function say(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
function head(title,sub,extra=''){return `<header class="top"><div><div class="title">${title}</div><div class="subtitle">${sub}</div></div><div class="grow"></div>${extra}<button class="ghost">•••</button></header>`}
function rail(active='genethub'){return `<aside class="rail"><div class="logo">◈ GeneHub</div><button class="primary wide" data-new>＋ 新会话</button><div class="eyebrow">项目</div>${projects.slice(0,3).map(p=>`<button class="navitem ${p[0]===active?'active':''}" data-project="${p[0]}"><span class="dot"></span>${p[0]}</button>`).join('')}<div class="eyebrow">最近</div><button class="navitem active">Agent Chat 交互重构</button><button class="navitem">登录状态修复</button></aside>`}
function messages(){return `<div class="messages"><div class="msg me"><div>重新设计 Agent Chat 的输入体验，先把项目和会话的关系简化。</div></div><div class="msg"><div class="avatar">G</div><div>项目不应该成为开始对话的表单门槛。用户先表达任务，系统负责继承、推荐或在真正需要文件权限时请求绑定。</div></div></div>`}
function composer({project='genethub',unbound=false,context='',label='描述任务，粘贴图片，或输入 / 使用命令…'}={}){return `<div class="composer" data-composer><div class="contextline">${project?`<button class="context ${unbound?'unbound':''}" data-project-trigger>${unbound?'＋ 连接项目':'▣ '+project+' ×'}</button>`:''}${context?`<span class="context">${context}</span>`:''}</div><div class="attachments"></div><div class="compose"><textarea rows="1" placeholder="${label}" aria-label="任务描述"></textarea></div><div class="voice" hidden><span class="wave">▂▅▇▃▆</span><span>正在聆听，转写会写入当前草稿</span><button class="ghost" data-voice-done>完成</button></div><div class="actions"><button class="ghost" data-attach>＋</button><input type="file" accept="image/*" multiple hidden><button class="pill" data-agent>Codex⌄</button><button class="pill" data-model>GPT-5.2 Codex⌄</button><button class="pill" data-mode>🛡 Agent · 高</button><button class="ghost" data-mic>◉</button><button class="send" data-send>↑</button></div></div>`}
function chatPage({title,sub,side=rail(),project='genethub',before='',right='',context=''}){return `<div class="shell">${side}<main class="main">${head(title,sub,'<button class="ghost">↗</button>')}<section class="stage">${messages()}</section><div class="composer-zone">${before}${composer({project,context})}<div class="helper">Enter 发送 · Shift Enter 换行 · 支持直接粘贴图片</div></div></main>${right}</div>`}
function renderFluid(){app.innerHTML=chatPage({title:'方案 01 · 自动继承',sub:'新会话立即开始，项目来自当前来源',context:'dev-agent'});bindCommon();document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>say('已立即创建新会话，并继承 genethub'))}
function renderRecommend(){app.innerHTML=`<div class="shell">${rail('')}<main class="main">${head('方案 02 · 意图推荐','先输入任务，项目不是前置问题')}<section class="stage"><div class="hero"><div class="subtitle">无项目新会话</div><h1>现在想完成什么？</h1><p>先描述任务。涉及代码时，GeneHub 会建议最合适的项目。</p></div></section><div class="composer-zone"><div class="recommend" data-recommend hidden><span>✨ 根据“登录、token”判断，建议使用 <b>genethub-cloud</b></span><div class="grow"></div><button class="primary" data-accept>使用</button><button class="ghost" data-dismiss>忽略</button></div>${composer({project:'',label:'例如：修复登录页面的 token 刷新问题…'})}</div></main></div>`;bindCommon();const ta=document.querySelector('textarea'),r=document.querySelector('[data-recommend]');ta.addEventListener('input',()=>r.hidden=ta.value.length<5);document.querySelector('[data-accept]').onclick=()=>{r.hidden=true;document.querySelector('.contextline').innerHTML='<button class="context" data-project-trigger>▣ genethub-cloud ×</button>';say('已添加项目，仅作用于当前会话')};document.querySelector('[data-dismiss]').onclick=()=>r.hidden=true}
function renderLauncher(){app.innerHTML=`<div class="shell">${rail('')}<main class="main">${head('方案 03 · 快捷起点','新建入口直接提供最近项目与无项目')}<section class="stage"><div class="hero"><h1>开始一个新任务</h1><p>选择起点后立即进入会话，不再经过项目详情页。</p><div class="launchgrid">${projects.map((p,i)=>`<button class="launch" data-launch="${p[0]}"><b>${i===3?'◇':'▣'} ${p[0]}</b><small>${p[1]}</small></button>`).join('')}<button class="launch" data-browse><b>⌕ 浏览全部项目</b><small>搜索、固定或打开本地目录</small></button><button class="launch" data-quick><b>⌘ 直接输入任务</b><small>稍后再确定项目</small></button></div></div></section></main></div>`;document.querySelectorAll('[data-launch]').forEach(b=>b.onclick=()=>{app.innerHTML=chatPage({title:'方案 03 · 快捷起点',sub:`从 ${b.dataset.launch} 创建`,project:b.dataset.launch==='无项目'?'':b.dataset.launch,side:rail(b.dataset.launch)});bindCommon()});document.querySelector('[data-browse]').onclick=()=>openProjectDialog(p=>say('已选择 '+p));document.querySelector('[data-quick]').onclick=()=>{app.innerHTML=chatPage({title:'方案 03 · 快捷起点',sub:'项目稍后确定',project:'',side:rail('')});bindCommon()}}
function renderCanvas(){const pside=`<aside class="projectrail"><div class="projecticons"><button>G</button><button>C</button><button>＋</button></div><div class="threads"><div class="title">genethub</div><button class="primary wide" data-new>＋ 项目内新会话</button><div class="eyebrow">对话</div><button class="navitem active">Agent Chat 交互</button><button class="navitem">CLI 错误处理</button><button class="navitem">语音协议</button></div></aside>`,right=`<aside class="inspector"><div class="eyebrow">本次任务</div><div class="card selected"><b>▣ genethub</b><small>工作区 · dev-agent</small></div><div class="eyebrow">执行者</div><button class="card selected wide" data-agent><b>Codex</b><small>GPT-5.2 Codex · 高</small></button><div class="eyebrow">权限</div><button class="card wide" data-mode><b>Agent 模式</b><small>修改前按规则确认</small></button><div class="eyebrow">上下文</div><button class="card wide"><b>＋ 添加文件或工具</b><small>当前约 8.2K tokens</small></button></aside>`;app.innerHTML=chatPage({title:'方案 04 · 项目导航',sub:'项目是稳定工作范围，会话从项目内部创建',side:pside,right,project:'',context:'▣ genethub · dev-agent'});bindCommon();document.querySelector('[data-new]').onclick=()=>say('已在 genethub 内创建新会话')}
function renderMobile(){app.innerHTML=`<div class="shell"><main class="main">${head('方案 05 · 按需绑定','普通对话零门槛，使用项目能力时再绑定')}<section class="stage"><div class="gate"><div class="subtitle">无项目 · 不访问文件</div><h1>直接开始对话</h1><p>粘贴图片和语音不需要项目。读取文件、运行命令或调用项目工具时才请求绑定。</p></div></section><div class="composer-zone">${composer({project:'',context:'◇ 无项目 · 点击绑定',label:'聊天，或描述需要操作项目的任务…'})}</div></main></div>`;bindCommon();const context=document.querySelector('.context');context.style.cursor='pointer';context.onclick=()=>openBindGate('绑定后 Agent 才能读取文件、执行命令和使用项目工具。')}
function bindCommon(opts={}){document.querySelectorAll('textarea').forEach(t=>{const grow=()=>{t.style.height='0';t.style.height=Math.min(t.scrollHeight,220)+'px'};t.oninput=grow;t.onpaste=e=>{const fs=[...e.clipboardData.files].filter(f=>f.type.startsWith('image/'));if(fs.length){e.preventDefault();addFiles(fs,t.closest('[data-composer]'))}};t.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();t.closest('[data-composer]').querySelector('[data-send]').click()}};grow()});document.querySelectorAll('[data-attach]').forEach(b=>{if(opts.gate)return;b.onclick=()=>{const i=b.parentElement.querySelector('input');i.click();i.onchange=()=>addFiles(i.files,b.closest('[data-composer]'))}});document.querySelectorAll('[data-project-trigger]').forEach(b=>b.onclick=()=>openProjectDialog(p=>{b.textContent='▣ '+p+' ×';say('项目已切换为 '+p)}));document.querySelectorAll('[data-agent]').forEach(b=>b.onclick=()=>openChoice('选择 Agent',agents,v=>{b.textContent=v+'⌄';say('Agent 已切换')}));document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>openChoice('选择模型',models,v=>{b.textContent=v+'⌄';say('模型设置用于下一条消息')},true));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>openMode());document.querySelectorAll('[data-mic]').forEach(b=>b.onclick=()=>{const c=b.closest('[data-composer]'),v=c.querySelector('.voice');v.hidden=!v.hidden;b.textContent=v.hidden?'◉':'■'});document.querySelectorAll('[data-voice-done]').forEach(b=>b.onclick=()=>{const c=b.closest('[data-composer]'),t=c.querySelector('textarea');t.value+=(t.value?' ':'')+'请把这个交互做成移动端优先。';t.dispatchEvent(new Event('input'));c.querySelector('.voice').hidden=true;c.querySelector('[data-mic]').textContent='◉'});document.querySelectorAll('[data-send]').forEach(b=>b.onclick=()=>{const c=b.closest('[data-composer]'),t=c.querySelector('textarea');if(!t.value.trim()&&!c.querySelector('.thumb'))return say('请输入消息或添加图片');b.textContent='■';b.style.background='var(--warn)';t.value='';t.dispatchEvent(new Event('input'));setTimeout(()=>{b.textContent='↑';b.style.background=''},1800);say('消息已发送，再次点击可停止')})}
function addFiles(files,c){[...files].filter(f=>f.type.startsWith('image/')).forEach(f=>{const u=URL.createObjectURL(f),d=document.createElement('button');d.className='thumb';d.innerHTML=`<img src="${u}" alt="${f.name}"><i>预览</i>`;d.onclick=()=>openPreview(u);c.querySelector('.attachments').append(d)});say('图片已添加，点击缩略图预览')}
function openPreview(u){overlay.hidden=false;overlay.innerHTML=`<div class="dialog" style="width:auto;background:transparent;border:0"><button class="close" data-close>×</button><img src="${u}" alt="图片大图预览" style="max-width:90vw;max-height:82dvh;border-radius:14px"></div>`;closeable()}
function openProjectDialog(done){overlay.hidden=false;overlay.innerHTML=`<section class="dialog"><div class="dialoghead"><h2>这次任务在哪里发生？</h2><button class="close" data-close>×</button></div><input class="search" placeholder="搜索项目或本地目录…"><div class="cards">${projects.map(p=>`<button class="card" data-value="${p[0]}"><b>${p[0]}</b><small>${p[1]}</small></button>`).join('')}</div></section>`;overlay.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>{done(b.dataset.value);overlay.hidden=true});closeable()}
function openChoice(title,items,done,filter=false){overlay.hidden=false;overlay.innerHTML=`<section class="dialog"><div class="dialoghead"><h2>${title}</h2><button class="close" data-close>×</button></div>${filter?'<input class="search" placeholder="搜索名称、提供商或能力…"><div class="tabs"><button class="tab active">全部</button><button class="tab">最近</button><button class="tab">收藏</button><button class="tab">视觉</button><button class="tab">本地</button></div>':''}<div class="cards">${items.map(x=>`<button class="card choice" data-value="${x[0]}"><b>${x[0]}</b><small>${x[1]}</small></button>`).join('')}</div></section>`;if(filter){const s=overlay.querySelector('.search');s.oninput=()=>overlay.querySelectorAll('.choice').forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(s.value.toLowerCase()))}overlay.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{done(b.dataset.value);overlay.hidden=true});closeable()}
function openMode(){openChoice('运行方式',[['询问模式','每次执行敏感操作前确认'],['Agent 模式','按项目规则自主执行'],['只读模式','只分析，不修改文件'],['高思考强度','质量优先，耗时更长']],v=>say('已选择 '+v))}
function openBindGate(text){overlay.hidden=false;overlay.innerHTML=`<section class="dialog"><div class="dialoghead"><h2>需要项目上下文</h2><button class="close" data-close>×</button></div><p style="color:var(--muted)">${text}</p><div class="cards">${projects.slice(0,3).map(p=>`<button class="card" data-value="${p[0]}"><b>${p[0]}</b><small>${p[1]}</small></button>`).join('')}</div></section>`;overlay.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>{overlay.hidden=true;document.querySelector('.contextline').innerHTML=`<button class="context">▣ ${b.dataset.value} ×</button>`;say('项目已绑定，现在可以选择文件')});closeable()}
function closeable(){overlay.querySelector('[data-close]').onclick=()=>overlay.hidden=true;overlay.onclick=e=>{if(e.target===overlay)overlay.hidden=true}}
({fluid:renderFluid,palette:renderRecommend,capsules:renderLauncher,canvas:renderCanvas,mobilefirst:renderMobile}[scheme]||renderFluid)();
