import type {
  FabricAuthority,
  FabricEndpointGrant,
  FabricRevocation,
} from "../contract/fabric.js";
import {
  decodeFabricOpenPayload,
  FabricKind,
  type FabricFrame,
  FABRIC_MAX_STREAM_CREDIT,
  FabricReset,
  MAX_OPERATION_METADATA_BYTES,
  newFabricStreamId,
  ZERO_STREAM_ID,
} from "./fabric-frame.js";

export interface FabricEndpointContext extends FabricEndpointGrant {
  /** Generated by the relay for this physical socket. Reconnects always differ. */
  connectionEpoch: string;
}

export interface FabricEndpointConnection {
  readonly context: Readonly<FabricEndpointContext>;
  /** The actual socket object, never a value supplied on the wire. */
  readonly socketIdentity: object;
  readonly streams: Map<string, FabricStreamLeg>;
  readonly pending: Map<string, symbol>;
  readonly tombstones: Map<string, number>;
  /** Bounded grace for frames already crossing the opposite socket at close. */
  readonly lateFrameBudgets: Map<string, number>;
  closed: boolean;
  strikes: number;
  send(frame: FabricFrame): void;
  close(code: number): void;
}

export interface FabricStreamLeg {
  readonly connection: FabricEndpointConnection;
  readonly localStreamId: string;
  binding: FabricPeerBinding;
  sentFin: boolean;
  lastDataSeq: bigint;
  sendCredit: bigint;
  sendWindow: bigint;
}

export interface FabricPeerBinding {
  readonly initiator: FabricStreamLeg;
  readonly responder: FabricStreamLeg;
  readonly routeHandle: string;
  readonly expiresAt: number;
  phase: "opening" | "active" | "closed";
}

export interface FabricCoreOptions {
  now?: () => number;
  streamId?: () => string;
  maxStrikes?: number;
  tombstoneMs?: number;
  maxTombstonesPerEndpoint?: number;
  maxLateFramesPerClosedStream?: number;
  revocationTombstoneMs?: number;
  maxRevocationTombstones?: number;
  maxConnectionGenerations?: number;
  maxPendingPerEndpoint?: number;
  maxPendingGlobal?: number;
  maxStreamsPerEndpoint?: number;
  maxStreamsGlobal?: number;
}

interface RevocationFence {
  expiresAt: number;
  sequence: number;
}

/**
 * Endpoint-neutral operation routing.
 *
 * There is intentionally no global stream-id table. Every lookup starts from
 * the actual connection object and then uses that connection's local id. The
 * peer may use the same local id as somebody else; the relay rewrites it on
 * every forwarded frame.
 */
export class FabricCore {
  private readonly endpoints = new Map<string, FabricEndpointConnection>();
  /**
   * Highest authority-issued admission generation observed for each endpoint.
   *
   * This deliberately outlives the socket. Otherwise an older authorization
   * response that was delayed in flight could become current after the newer
   * socket disconnected. Expiring client identities are pruned after their
   * authority expiry; non-expiring node identities are stable and remain
   * fenced for this process lifetime. Reusing either with a reset generation
   * is invalid.
   */
  private readonly connectionGenerations = new Map<
    string,
    { generation: number; expiresAt: number | null }
  >();
  private readonly routes = new Map<string, FabricPeerBinding>();
  private readonly revokedEndpoints = new Map<string, RevocationFence>();
  private readonly revokedRoutes = new Map<string, RevocationFence>();
  private revocationSequence = 0;
  /** Highest forgotten event; older in-flight grants fail closed. */
  private revocationFloor = 0;
  private readonly now: () => number;
  private readonly nextStreamId: () => string;
  private readonly maxStrikes: number;
  private readonly tombstoneMs: number;
  private readonly maxTombstones: number;
  private readonly maxLateFramesPerClosedStream: number;
  private readonly revocationTombstoneMs: number;
  private readonly maxRevocationTombstones: number;
  private readonly maxConnectionGenerations: number;
  private readonly maxPendingPerEndpoint: number;
  private readonly maxPendingGlobal: number;
  private readonly maxStreamsPerEndpoint: number;
  private readonly maxStreamsGlobal: number;
  private pendingCount = 0;

  constructor(
    private readonly authority: FabricAuthority,
    options: FabricCoreOptions = {},
  ) {
    this.now = options.now ?? Date.now;
    this.nextStreamId = options.streamId ?? newFabricStreamId;
    this.maxStrikes = options.maxStrikes ?? 8;
    this.tombstoneMs = options.tombstoneMs ?? 60_000;
    this.maxTombstones = options.maxTombstonesPerEndpoint ?? 512;
    this.maxLateFramesPerClosedStream =
      options.maxLateFramesPerClosedStream ?? 256;
    this.revocationTombstoneMs = options.revocationTombstoneMs ?? 5 * 60_000;
    this.maxRevocationTombstones = options.maxRevocationTombstones ?? 4_096;
    this.maxConnectionGenerations = options.maxConnectionGenerations ?? 100_000;
    this.maxPendingPerEndpoint = options.maxPendingPerEndpoint ?? 32;
    this.maxPendingGlobal = options.maxPendingGlobal ?? 1024;
    this.maxStreamsPerEndpoint = options.maxStreamsPerEndpoint ?? 256;
    this.maxStreamsGlobal = options.maxStreamsGlobal ?? 100_000;
  }

  revocationCheckpoint(): number {
    return this.revocationSequence;
  }

  register(
    connection: FabricEndpointConnection,
    revocationCheckpoint = this.revocationSequence,
  ): FabricEndpointConnection | null {
    this.pruneRevocations();
    this.pruneConnectionGenerations();
    if (
      this.wasRevokedSince(
        this.revokedEndpoints,
        connection.context.revocationHandle,
        revocationCheckpoint,
      )
    ) {
      connection.closed = true;
      connection.close(4403);
      return null;
    }
    const handle = connection.context.endpointHandle;
    const generation = connection.context.connectionGeneration;
    const observed = this.connectionGenerations.get(handle);
    if (observed !== undefined && generation <= observed.generation) {
      connection.closed = true;
      connection.close(4409);
      return null;
    }
    if (
      observed === undefined &&
      this.connectionGenerations.size >= this.maxConnectionGenerations
    ) {
      connection.closed = true;
      connection.close(4429);
      return null;
    }
    this.connectionGenerations.set(handle, {
      generation,
      expiresAt: parseExpiry(connection.context.expiresAt),
    });
    const previous = this.endpoints.get(handle) ?? null;
    if (previous && previous !== connection) {
      this.unregister(previous, FabricReset.EndpointClosed);
    }
    this.endpoints.set(handle, connection);
    return previous;
  }

  unregister(
    connection: FabricEndpointConnection,
    reason: FabricReset = FabricReset.EndpointClosed,
  ): void {
    if (connection.closed) return;
    connection.closed = true;
    if (this.endpoints.get(connection.context.endpointHandle) === connection) {
      this.endpoints.delete(connection.context.endpointHandle);
    }
    this.pendingCount = Math.max(0, this.pendingCount - connection.pending.size);
    connection.pending.clear();
    connection.tombstones.clear();
    connection.lateFrameBudgets.clear();

    const bindings = new Set([...connection.streams.values()].map((leg) => leg.binding));
    for (const binding of bindings) {
      this.closeBinding(binding, reason, connection);
    }
    connection.streams.clear();
  }

  current(endpointHandle: string): FabricEndpointConnection | null {
    return this.endpoints.get(endpointHandle) ?? null;
  }

  async handle(connection: FabricEndpointConnection, frame: FabricFrame): Promise<void> {
    if (!this.isCurrent(connection)) return;
    if (this.expireEndpoint(connection)) return;
    this.pruneTombstones(connection);

    const existing = connection.streams.get(frame.streamId);
    if (existing && existing.binding.expiresAt <= this.now()) {
      this.closeBinding(existing.binding, FabricReset.Expired);
      return;
    }

    // Any frame that races an OPEN authorization for the same local id
    // cancels that reservation. In particular RESET must not be followed by a
    // delayed grant resurrecting a stream the endpoint already abandoned.
    if (frame.kind !== FabricKind.Open && connection.pending.has(frame.streamId)) {
      this.cancelPending(connection, frame.streamId);
      if (frame.kind === FabricKind.Reset) {
        this.remember(connection, frame.streamId);
      } else {
        this.reject(connection, frame.streamId, FabricReset.ProtocolViolation);
      }
      return;
    }

    switch (frame.kind) {
      case FabricKind.Open:
        await this.open(connection, frame);
        return;
      case FabricKind.Accept:
        this.accept(connection, frame);
        return;
      case FabricKind.Data:
        this.data(connection, frame);
        return;
      case FabricKind.WindowUpdate:
        this.windowUpdate(connection, frame);
        return;
      case FabricKind.Fin:
        this.fin(connection, frame);
        return;
      case FabricKind.Reset:
        this.reset(connection, frame);
        return;
      case FabricKind.Ping:
        if (frame.payload.length !== 0) {
          this.strike(connection);
          return;
        }
        connection.send({
          kind: FabricKind.Pong,
          streamId: ZERO_STREAM_ID,
          value: frame.value,
          payload: frame.payload,
        });
        return;
      case FabricKind.Pong:
        if (frame.payload.length !== 0) this.strike(connection);
        return;
      case FabricKind.Incoming:
        this.unknownOrViolation(connection, frame.streamId);
        return;
    }
  }

  revoke(revocation: FabricRevocation): void {
    if (revocation.target === "route") {
      this.rememberRevocation(this.revokedRoutes, revocation.handle);
      const binding = this.routes.get(revocation.handle);
      if (binding) this.closeBinding(binding, FabricReset.Revoked);
      return;
    }
    this.rememberRevocation(this.revokedEndpoints, revocation.handle);
    for (const connection of [...this.endpoints.values()]) {
      if (connection.context.revocationHandle !== revocation.handle) continue;
      this.unregister(connection, FabricReset.Revoked);
      connection.close(4403);
    }
  }

  sweepExpired(): void {
    this.pruneRevocations();
    const now = this.now();
    for (const connection of [...this.endpoints.values()]) {
      this.pruneTombstones(connection);
      const expiry = parseExpiry(connection.context.expiresAt);
      if (expiry !== null && expiry <= now) {
        this.unregister(connection, FabricReset.Expired);
        connection.close(4408);
      }
    }
    for (const binding of [...this.routes.values()]) {
      if (binding.expiresAt <= now) this.closeBinding(binding, FabricReset.Expired);
    }
    this.pruneConnectionGenerations();
  }

  stats(): { endpoints: number; streams: number; pendingOpens: number } {
    return {
      endpoints: this.endpoints.size,
      streams: this.routes.size,
      pendingOpens: this.pendingCount,
    };
  }

  private async open(
    source: FabricEndpointConnection,
    frame: FabricFrame,
  ): Promise<void> {
    if (
      source.streams.has(frame.streamId) ||
      source.pending.has(frame.streamId) ||
      source.tombstones.has(frame.streamId)
    ) {
      const existing = source.streams.get(frame.streamId);
      if (existing) this.closeBinding(existing.binding, FabricReset.DuplicateStream);
      else {
        // A second OPEN with the same connection-local id cancels an
        // authorization already in flight. Leaving the reservation in place
        // would let the first asynchronous result create a binding after we
        // had told the endpoint that the id was rejected.
        this.cancelPending(source, frame.streamId);
        this.reject(source, frame.streamId, FabricReset.DuplicateStream);
      }
      return;
    }

    const opening = decodeFabricOpenPayload(frame.payload);
    if (!opening || !validInitialCredit(frame.value)) {
      this.reject(source, frame.streamId, FabricReset.MalformedOpen);
      return;
    }

    if (
      source.pending.size >= this.maxPendingPerEndpoint ||
      this.pendingCount >= this.maxPendingGlobal ||
      source.streams.size >= this.maxStreamsPerEndpoint ||
      this.routes.size >= this.maxStreamsGlobal
    ) {
      this.reject(source, frame.streamId, FabricReset.TooSlow);
      return;
    }

    const reservation = Symbol(frame.streamId);
    const revocationCheckpoint = this.revocationSequence;
    source.pending.set(frame.streamId, reservation);
    this.pendingCount += 1;
    let grant;
    try {
      grant = await this.authority.authorizeRoute(
        source.context.endpointHandle,
        opening.routeTicket,
      );
    } catch {
      if (
        this.isCurrent(source) &&
        source.pending.get(frame.streamId) === reservation
      ) {
        this.cancelPending(source, frame.streamId);
        // Control unavailability is transient, unlike an authoritative null.
        // TooSlow is the existing retryable stream-local reset reason.
        this.reject(source, frame.streamId, FabricReset.TooSlow, false);
      }
      return;
    }

    if (
      !this.isCurrent(source) ||
      source.pending.get(frame.streamId) !== reservation
    ) {
      return;
    }
    if (this.expireEndpoint(source)) return;
    this.cancelPending(source, frame.streamId);

    if (!grant) {
      this.reject(source, frame.streamId, FabricReset.RouteDenied, false);
      return;
    }
    this.pruneRevocations();
    if (
      this.wasRevokedSince(
        this.revokedRoutes,
        grant.routeHandle,
        revocationCheckpoint,
      )
    ) {
      this.reject(source, frame.streamId, FabricReset.Revoked, false);
      return;
    }
    if (this.routes.has(grant.routeHandle)) {
      this.reject(source, frame.streamId, FabricReset.ProtocolViolation);
      return;
    }
    const expiresAt = parseExpiry(grant.expiresAt);
    if (expiresAt === null || expiresAt <= this.now()) {
      this.reject(source, frame.streamId, FabricReset.Expired, false);
      return;
    }

    const target = this.endpoints.get(grant.targetEndpointHandle);
    if (!target || target.closed || this.expireEndpoint(target)) {
      this.reject(source, frame.streamId, FabricReset.TargetOffline, false);
      return;
    }
    if (target.streams.size >= this.maxStreamsPerEndpoint) {
      this.reject(source, frame.streamId, FabricReset.TooSlow, false);
      return;
    }
    const targetStreamId = this.allocateStreamId(target);
    if (!targetStreamId) {
      this.reject(source, frame.streamId, FabricReset.TargetOffline, false);
      return;
    }

    const binding = {} as FabricPeerBinding;
    const initiator: FabricStreamLeg = {
      connection: source,
      localStreamId: frame.streamId,
      binding,
      sentFin: false,
      lastDataSeq: 0n,
      sendCredit: 0n,
      sendWindow: 0n,
    };
    const responder: FabricStreamLeg = {
      connection: target,
      localStreamId: targetStreamId,
      binding,
      sentFin: false,
      lastDataSeq: 0n,
      sendCredit: frame.value,
      sendWindow: frame.value,
    };
    Object.assign(binding, {
      initiator,
      responder,
      routeHandle: grant.routeHandle,
      expiresAt,
      phase: "opening",
    } satisfies Omit<FabricPeerBinding, "initiator" | "responder"> & {
      initiator: FabricStreamLeg;
      responder: FabricStreamLeg;
    });

    source.streams.set(frame.streamId, initiator);
    target.streams.set(targetStreamId, responder);
    this.routes.set(grant.routeHandle, binding);
    target.send({
      kind: FabricKind.Incoming,
      streamId: targetStreamId,
      value: frame.value,
      payload: opening.opaqueHello,
    });
  }

  private accept(connection: FabricEndpointConnection, frame: FabricFrame): void {
    const leg = connection.streams.get(frame.streamId);
    if (!leg) return this.unknownOrViolation(connection, frame.streamId);
    const binding = leg.binding;
    if (
      binding.phase !== "opening" ||
      leg !== binding.responder ||
      !validInitialCredit(frame.value) ||
      frame.payload.length > MAX_OPERATION_METADATA_BYTES
    ) {
      this.closeBinding(binding, FabricReset.ProtocolViolation);
      this.strike(connection);
      return;
    }
    binding.phase = "active";
    const peer = binding.initiator;
    peer.sendCredit = frame.value;
    peer.sendWindow = frame.value;
    peer.connection.send({
      kind: FabricKind.Accept,
      streamId: peer.localStreamId,
      value: frame.value,
      payload: frame.payload,
    });
  }

  private data(connection: FabricEndpointConnection, frame: FabricFrame): void {
    const leg = connection.streams.get(frame.streamId);
    if (!leg) return this.unknownOrViolation(connection, frame.streamId);
    const cost = BigInt(frame.payload.length);
    if (
      leg.binding.phase !== "active" ||
      leg.sentFin ||
      frame.value !== leg.lastDataSeq + 1n ||
      cost <= 0n ||
      cost > leg.sendCredit
    ) {
      this.closeBinding(leg.binding, FabricReset.ProtocolViolation);
      this.strike(connection);
      return;
    }
    leg.sendCredit -= cost;
    leg.lastDataSeq = frame.value;
    this.forward(leg, frame);
  }

  private windowUpdate(
    connection: FabricEndpointConnection,
    frame: FabricFrame,
  ): void {
    const leg = connection.streams.get(frame.streamId);
    if (!leg) return this.unknownOrViolation(connection, frame.streamId);
    const peer = this.peerOf(leg);
    if (
      leg.binding.phase !== "active" ||
      frame.value === 0n ||
      frame.payload.length !== 0 ||
      peer.sendCredit + frame.value > peer.sendWindow
    ) {
      this.closeBinding(leg.binding, FabricReset.ProtocolViolation);
      this.strike(connection);
      return;
    }
    peer.sendCredit += frame.value;
    this.forward(leg, frame);
  }

  private fin(connection: FabricEndpointConnection, frame: FabricFrame): void {
    const leg = connection.streams.get(frame.streamId);
    if (!leg) return this.unknownOrViolation(connection, frame.streamId);
    if (
      leg.binding.phase !== "active" ||
      leg.sentFin ||
      frame.value !== 0n ||
      frame.payload.length !== 0
    ) {
      this.closeBinding(leg.binding, FabricReset.ProtocolViolation);
      this.strike(connection);
      return;
    }
    leg.sentFin = true;
    this.forward(leg, frame);
    const peer = this.peerOf(leg);
    if (peer.sentFin) this.closeBinding(leg.binding, null);
  }

  private reset(connection: FabricEndpointConnection, frame: FabricFrame): void {
    const leg = connection.streams.get(frame.streamId);
    if (!leg) return;
    if (frame.value === 0n || frame.payload.length !== 0) {
      this.closeBinding(leg.binding, FabricReset.ProtocolViolation);
      this.strike(connection);
      return;
    }
    const peer = this.peerOf(leg);
    peer.connection.send({
      kind: FabricKind.Reset,
      streamId: peer.localStreamId,
      value: frame.value,
      payload: Buffer.alloc(0),
    });
    this.closeBinding(leg.binding, null);
  }

  private forward(leg: FabricStreamLeg, frame: FabricFrame): void {
    const peer = this.peerOf(leg);
    peer.connection.send({
      kind: frame.kind,
      streamId: peer.localStreamId,
      value: frame.value,
      payload: frame.payload,
    });
  }

  private peerOf(leg: FabricStreamLeg): FabricStreamLeg {
    return leg === leg.binding.initiator
      ? leg.binding.responder
      : leg.binding.initiator;
  }

  private closeBinding(
    binding: FabricPeerBinding,
    reason: FabricReset | null,
    silent?: FabricEndpointConnection,
  ): void {
    if (binding.phase === "closed") return;
    binding.phase = "closed";
    this.routes.delete(binding.routeHandle);

    for (const leg of [binding.initiator, binding.responder]) {
      leg.connection.streams.delete(leg.localStreamId);
      this.remember(
        leg.connection,
        leg.localStreamId,
        this.maxLateFramesPerClosedStream,
      );
      if (
        reason !== null &&
        leg.connection !== silent &&
        this.isCurrent(leg.connection)
      ) {
        leg.connection.send({
          kind: FabricKind.Reset,
          streamId: leg.localStreamId,
          value: BigInt(reason),
          payload: Buffer.alloc(0),
        });
      }
    }
  }

  private unknownOrViolation(
    connection: FabricEndpointConnection,
    streamId: string,
  ): void {
    if (!connection.tombstones.has(streamId)) {
      this.reject(connection, streamId, FabricReset.UnknownStream);
      return;
    }
    const remaining = connection.lateFrameBudgets.get(streamId) ?? 0;
    if (remaining > 0) {
      if (remaining === 1) connection.lateFrameBudgets.delete(streamId);
      else connection.lateFrameBudgets.set(streamId, remaining - 1);
      return;
    }
    this.strike(connection);
  }

  private reject(
    connection: FabricEndpointConnection,
    streamId: string,
    reason: FabricReset,
    countStrike = true,
  ): void {
    if (this.isCurrent(connection)) {
      connection.send({
        kind: FabricKind.Reset,
        streamId,
        value: BigInt(reason),
        payload: Buffer.alloc(0),
      });
    }
    this.remember(connection, streamId);
    if (countStrike) this.strike(connection);
  }

  private strike(connection: FabricEndpointConnection): void {
    connection.strikes += 1;
    if (connection.strikes < this.maxStrikes) return;
    this.unregister(connection, FabricReset.ProtocolViolation);
    connection.close(4400);
  }

  private cancelPending(connection: FabricEndpointConnection, streamId: string): void {
    if (!connection.pending.delete(streamId)) return;
    this.pendingCount = Math.max(0, this.pendingCount - 1);
  }

  private allocateStreamId(connection: FabricEndpointConnection): string | null {
    this.pruneTombstones(connection);
    for (let attempt = 0; attempt < 32; attempt += 1) {
      const candidate = this.nextStreamId();
      if (
        candidate !== ZERO_STREAM_ID &&
        !connection.streams.has(candidate) &&
        !connection.pending.has(candidate) &&
        !connection.tombstones.has(candidate)
      ) {
        return candidate;
      }
    }
    return null;
  }

  private remember(
    connection: FabricEndpointConnection,
    streamId: string,
    lateFrameBudget = 0,
  ): void {
    connection.tombstones.set(streamId, this.now() + this.tombstoneMs);
    if (lateFrameBudget > 0) {
      connection.lateFrameBudgets.set(streamId, lateFrameBudget);
    } else {
      connection.lateFrameBudgets.delete(streamId);
    }
    this.pruneTombstones(connection);
    while (connection.tombstones.size > this.maxTombstones) {
      const oldest = connection.tombstones.keys().next().value as string | undefined;
      if (!oldest) break;
      connection.tombstones.delete(oldest);
      connection.lateFrameBudgets.delete(oldest);
    }
  }

  private pruneTombstones(connection: FabricEndpointConnection): void {
    const now = this.now();
    for (const [streamId, expiresAt] of connection.tombstones) {
      if (expiresAt <= now) {
        connection.tombstones.delete(streamId);
        connection.lateFrameBudgets.delete(streamId);
      }
    }
  }

  private rememberRevocation(
    table: Map<string, RevocationFence>,
    handle: string,
  ): void {
    // Delete first so refreshing an existing handle also refreshes its
    // insertion order for bounded eviction.
    table.delete(handle);
    table.set(handle, {
      expiresAt: this.now() + this.revocationTombstoneMs,
      sequence: ++this.revocationSequence,
    });
    while (table.size > this.maxRevocationTombstones) {
      const oldest = table.entries().next().value as
        | [string, RevocationFence]
        | undefined;
      if (!oldest) break;
      table.delete(oldest[0]);
      this.revocationFloor = Math.max(this.revocationFloor, oldest[1].sequence);
    }
  }

  private pruneRevocations(): void {
    const now = this.now();
    for (const table of [this.revokedEndpoints, this.revokedRoutes]) {
      for (const [handle, fence] of table) {
        if (fence.expiresAt <= now) {
          table.delete(handle);
          this.revocationFloor = Math.max(this.revocationFloor, fence.sequence);
        }
      }
    }
  }

  private wasRevokedSince(
    table: Map<string, RevocationFence>,
    handle: string,
    checkpoint: number,
  ): boolean {
    return table.has(handle) || checkpoint < this.revocationFloor;
  }

  private pruneConnectionGenerations(): void {
    const now = this.now();
    for (const [handle, fence] of this.connectionGenerations) {
      if (
        fence.expiresAt !== null &&
        fence.expiresAt <= now &&
        !this.endpoints.has(handle)
      ) {
        this.connectionGenerations.delete(handle);
      }
    }
  }

  private expireEndpoint(connection: FabricEndpointConnection): boolean {
    const expiry = parseExpiry(connection.context.expiresAt);
    if (expiry === null || expiry > this.now()) return false;
    this.unregister(connection, FabricReset.Expired);
    connection.close(4408);
    return true;
  }

  private isCurrent(connection: FabricEndpointConnection): boolean {
    return (
      !connection.closed &&
      this.endpoints.get(connection.context.endpointHandle) === connection
    );
  }
}

function parseExpiry(value: string | null): number | null {
  if (value === null) return null;
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function validInitialCredit(value: bigint): boolean {
  return value > 0n && value <= BigInt(FABRIC_MAX_STREAM_CREDIT);
}
