import type {
  FabricAuthority,
  FabricEndpointGrant,
  FabricRevocation,
} from "../contract/fabric.js";
import {
  decodeFabricOpenPayload,
  FabricKind,
  type FabricFrame,
  FabricReset,
  newFabricStreamId,
  ZERO_STREAM_ID,
} from "./fabric-frame.js";

export interface FabricEndpointContext extends FabricEndpointGrant {
  /** Generated by the relay for this physical socket. Reconnects always differ. */
  connectionEpoch: string;
}

export interface FabricEndpointConnection {
  readonly context: Readonly<FabricEndpointContext>;
  /** The actual socket object, never a value supplied on the wire. */
  readonly socketIdentity: object;
  readonly streams: Map<string, FabricStreamLeg>;
  readonly pending: Map<string, symbol>;
  readonly tombstones: Map<string, number>;
  closed: boolean;
  strikes: number;
  send(frame: FabricFrame): void;
  close(code: number): void;
}

export interface FabricStreamLeg {
  readonly connection: FabricEndpointConnection;
  readonly localStreamId: string;
  binding: FabricPeerBinding;
  sentFin: boolean;
  lastDataSeq: bigint;
}

export interface FabricPeerBinding {
  readonly initiator: FabricStreamLeg;
  readonly responder: FabricStreamLeg;
  readonly routeHandle: string;
  readonly expiresAt: number;
  phase: "opening" | "active" | "closed";
}

export interface FabricCoreOptions {
  now?: () => number;
  streamId?: () => string;
  maxStrikes?: number;
  tombstoneMs?: number;
  maxTombstonesPerEndpoint?: number;
  revocationTombstoneMs?: number;
  maxRevocationTombstones?: number;
}

/**
 * Endpoint-neutral operation routing.
 *
 * There is intentionally no global stream-id table. Every lookup starts from
 * the actual connection object and then uses that connection's local id. The
 * peer may use the same local id as somebody else; the relay rewrites it on
 * every forwarded frame.
 */
export class FabricCore {
  private readonly endpoints = new Map<string, FabricEndpointConnection>();
  private readonly routes = new Map<string, FabricPeerBinding>();
  private readonly revokedEndpoints = new Map<string, number>();
  private readonly revokedRoutes = new Map<string, number>();
  private readonly now: () => number;
  private readonly nextStreamId: () => string;
  private readonly maxStrikes: number;
  private readonly tombstoneMs: number;
  private readonly maxTombstones: number;
  private readonly revocationTombstoneMs: number;
  private readonly maxRevocationTombstones: number;

  constructor(
    private readonly authority: FabricAuthority,
    options: FabricCoreOptions = {},
  ) {
    this.now = options.now ?? Date.now;
    this.nextStreamId = options.streamId ?? newFabricStreamId;
    this.maxStrikes = options.maxStrikes ?? 8;
    this.tombstoneMs = options.tombstoneMs ?? 60_000;
    this.maxTombstones = options.maxTombstonesPerEndpoint ?? 512;
    this.revocationTombstoneMs = options.revocationTombstoneMs ?? 5 * 60_000;
    this.maxRevocationTombstones = options.maxRevocationTombstones ?? 4_096;
  }

  register(connection: FabricEndpointConnection): FabricEndpointConnection | null {
    this.pruneRevocations();
    if (this.revokedEndpoints.has(connection.context.revocationHandle)) {
      connection.closed = true;
      connection.close(4403);
      return null;
    }
    const handle = connection.context.endpointHandle;
    const previous = this.endpoints.get(handle) ?? null;
    if (previous && previous !== connection) {
      this.unregister(previous, FabricReset.EndpointClosed);
    }
    this.endpoints.set(handle, connection);
    return previous;
  }

  unregister(
    connection: FabricEndpointConnection,
    reason: FabricReset = FabricReset.EndpointClosed,
  ): void {
    if (connection.closed) return;
    connection.closed = true;
    if (this.endpoints.get(connection.context.endpointHandle) === connection) {
      this.endpoints.delete(connection.context.endpointHandle);
    }
    connection.pending.clear();

    const bindings = new Set([...connection.streams.values()].map((leg) => leg.binding));
    for (const binding of bindings) {
      this.closeBinding(binding, reason, connection);
    }
    connection.streams.clear();
  }

  current(endpointHandle: string): FabricEndpointConnection | null {
    return this.endpoints.get(endpointHandle) ?? null;
  }

  async handle(connection: FabricEndpointConnection, frame: FabricFrame): Promise<void> {
    if (!this.isCurrent(connection)) return;
    this.pruneTombstones(connection);

    switch (frame.kind) {
      case FabricKind.Open:
        await this.open(connection, frame);
        return;
      case FabricKind.Accept:
        this.accept(connection, frame);
        return;
      case FabricKind.Data:
        this.data(connection, frame);
        return;
      case FabricKind.WindowUpdate:
        this.windowUpdate(connection, frame);
        return;
      case FabricKind.Fin:
        this.fin(connection, frame);
        return;
      case FabricKind.Reset:
        this.reset(connection, frame);
        return;
      case FabricKind.Ping:
        connection.send({
          kind: FabricKind.Pong,
          streamId: ZERO_STREAM_ID,
          value: frame.value,
          payload: frame.payload,
        });
        return;
      case FabricKind.Pong:
        return;
      case FabricKind.Incoming:
        this.unknownOrViolation(connection, frame.streamId);
        return;
    }
  }

  revoke(revocation: FabricRevocation): void {
    if (revocation.target === "route") {
      this.rememberRevocation(this.revokedRoutes, revocation.handle);
      const binding = this.routes.get(revocation.handle);
      if (binding) this.closeBinding(binding, FabricReset.Revoked);
      return;
    }
    this.rememberRevocation(this.revokedEndpoints, revocation.handle);
    for (const connection of [...this.endpoints.values()]) {
      if (connection.context.revocationHandle !== revocation.handle) continue;
      this.unregister(connection, FabricReset.Revoked);
      connection.close(4403);
    }
  }

  sweepExpired(): void {
    this.pruneRevocations();
    const now = this.now();
    for (const connection of [...this.endpoints.values()]) {
      const expiry = parseExpiry(connection.context.expiresAt);
      if (expiry !== null && expiry <= now) {
        this.unregister(connection, FabricReset.Expired);
        connection.close(4408);
      }
    }
    for (const binding of [...this.routes.values()]) {
      if (binding.expiresAt <= now) this.closeBinding(binding, FabricReset.Expired);
    }
  }

  stats(): { endpoints: number; streams: number; pendingOpens: number } {
    let pendingOpens = 0;
    for (const endpoint of this.endpoints.values()) pendingOpens += endpoint.pending.size;
    return {
      endpoints: this.endpoints.size,
      streams: this.routes.size,
      pendingOpens,
    };
  }

  private async open(
    source: FabricEndpointConnection,
    frame: FabricFrame,
  ): Promise<void> {
    if (
      source.streams.has(frame.streamId) ||
      source.pending.has(frame.streamId) ||
      source.tombstones.has(frame.streamId)
    ) {
      const existing = source.streams.get(frame.streamId);
      if (existing) this.closeBinding(existing.binding, FabricReset.DuplicateStream);
      else {
        // A second OPEN with the same connection-local id cancels an
        // authorization already in flight. Leaving the reservation in place
        // would let the first asynchronous result create a binding after we
        // had told the endpoint that the id was rejected.
        source.pending.delete(frame.streamId);
        this.reject(source, frame.streamId, FabricReset.DuplicateStream);
      }
      return;
    }

    const opening = decodeFabricOpenPayload(frame.payload);
    if (!opening || frame.value !== 0n) {
      this.reject(source, frame.streamId, FabricReset.MalformedOpen);
      return;
    }

    const reservation = Symbol(frame.streamId);
    source.pending.set(frame.streamId, reservation);
    const grant = await this.authority
      .authorizeRoute(source.context.endpointHandle, opening.routeTicket)
      .catch(() => null);

    if (
      !this.isCurrent(source) ||
      source.pending.get(frame.streamId) !== reservation
    ) {
      return;
    }
    source.pending.delete(frame.streamId);

    if (!grant) {
      this.reject(source, frame.streamId, FabricReset.RouteDenied, false);
      return;
    }
    this.pruneRevocations();
    if (this.revokedRoutes.has(grant.routeHandle)) {
      this.reject(source, frame.streamId, FabricReset.Revoked, false);
      return;
    }
    if (this.routes.has(grant.routeHandle)) {
      this.reject(source, frame.streamId, FabricReset.ProtocolViolation);
      return;
    }
    const expiresAt = parseExpiry(grant.expiresAt);
    if (expiresAt === null || expiresAt <= this.now()) {
      this.reject(source, frame.streamId, FabricReset.Expired, false);
      return;
    }

    const target = this.endpoints.get(grant.targetEndpointHandle);
    if (!target || target.closed) {
      this.reject(source, frame.streamId, FabricReset.TargetOffline, false);
      return;
    }
    const targetStreamId = this.allocateStreamId(target);
    if (!targetStreamId) {
      this.reject(source, frame.streamId, FabricReset.TargetOffline, false);
      return;
    }

    const binding = {} as FabricPeerBinding;
    const initiator: FabricStreamLeg = {
      connection: source,
      localStreamId: frame.streamId,
      binding,
      sentFin: false,
      lastDataSeq: 0n,
    };
    const responder: FabricStreamLeg = {
      connection: target,
      localStreamId: targetStreamId,
      binding,
      sentFin: false,
      lastDataSeq: 0n,
    };
    Object.assign(binding, {
      initiator,
      responder,
      routeHandle: grant.routeHandle,
      expiresAt,
      phase: "opening",
    } satisfies Omit<FabricPeerBinding, "initiator" | "responder"> & {
      initiator: FabricStreamLeg;
      responder: FabricStreamLeg;
    });

    source.streams.set(frame.streamId, initiator);
    target.streams.set(targetStreamId, responder);
    this.routes.set(grant.routeHandle, binding);
    target.send({
      kind: FabricKind.Incoming,
      streamId: targetStreamId,
      value: 0n,
      payload: opening.opaqueHello,
    });
  }

  private accept(connection: FabricEndpointConnection, frame: FabricFrame): void {
    const leg = connection.streams.get(frame.streamId);
    if (!leg) return this.unknownOrViolation(connection, frame.streamId);
    const binding = leg.binding;
    if (
      binding.phase !== "opening" ||
      leg !== binding.responder ||
      frame.value !== 0n
    ) {
      this.closeBinding(binding, FabricReset.ProtocolViolation);
      this.strike(connection);
      return;
    }
    binding.phase = "active";
    const peer = binding.initiator;
    peer.connection.send({
      kind: FabricKind.Accept,
      streamId: peer.localStreamId,
      value: 0n,
      payload: frame.payload,
    });
  }

  private data(connection: FabricEndpointConnection, frame: FabricFrame): void {
    const leg = connection.streams.get(frame.streamId);
    if (!leg) return this.unknownOrViolation(connection, frame.streamId);
    if (
      leg.binding.phase !== "active" ||
      leg.sentFin ||
      frame.value !== leg.lastDataSeq + 1n
    ) {
      this.closeBinding(leg.binding, FabricReset.ProtocolViolation);
      this.strike(connection);
      return;
    }
    leg.lastDataSeq = frame.value;
    this.forward(leg, frame);
  }

  private windowUpdate(
    connection: FabricEndpointConnection,
    frame: FabricFrame,
  ): void {
    const leg = connection.streams.get(frame.streamId);
    if (!leg) return this.unknownOrViolation(connection, frame.streamId);
    if (leg.binding.phase !== "active" || frame.value === 0n || frame.payload.length !== 0) {
      this.closeBinding(leg.binding, FabricReset.ProtocolViolation);
      this.strike(connection);
      return;
    }
    this.forward(leg, frame);
  }

  private fin(connection: FabricEndpointConnection, frame: FabricFrame): void {
    const leg = connection.streams.get(frame.streamId);
    if (!leg) return this.unknownOrViolation(connection, frame.streamId);
    if (
      leg.binding.phase !== "active" ||
      leg.sentFin ||
      frame.value !== 0n ||
      frame.payload.length !== 0
    ) {
      this.closeBinding(leg.binding, FabricReset.ProtocolViolation);
      this.strike(connection);
      return;
    }
    leg.sentFin = true;
    this.forward(leg, frame);
    const peer = this.peerOf(leg);
    if (peer.sentFin) this.closeBinding(leg.binding, null);
  }

  private reset(connection: FabricEndpointConnection, frame: FabricFrame): void {
    const leg = connection.streams.get(frame.streamId);
    if (!leg) return;
    const peer = this.peerOf(leg);
    peer.connection.send({
      kind: FabricKind.Reset,
      streamId: peer.localStreamId,
      value: frame.value,
      payload: Buffer.alloc(0),
    });
    this.closeBinding(leg.binding, null);
  }

  private forward(leg: FabricStreamLeg, frame: FabricFrame): void {
    const peer = this.peerOf(leg);
    peer.connection.send({
      kind: frame.kind,
      streamId: peer.localStreamId,
      value: frame.value,
      payload: frame.payload,
    });
  }

  private peerOf(leg: FabricStreamLeg): FabricStreamLeg {
    return leg === leg.binding.initiator
      ? leg.binding.responder
      : leg.binding.initiator;
  }

  private closeBinding(
    binding: FabricPeerBinding,
    reason: FabricReset | null,
    silent?: FabricEndpointConnection,
  ): void {
    if (binding.phase === "closed") return;
    binding.phase = "closed";
    this.routes.delete(binding.routeHandle);

    for (const leg of [binding.initiator, binding.responder]) {
      leg.connection.streams.delete(leg.localStreamId);
      this.remember(leg.connection, leg.localStreamId);
      if (
        reason !== null &&
        leg.connection !== silent &&
        this.isCurrent(leg.connection)
      ) {
        leg.connection.send({
          kind: FabricKind.Reset,
          streamId: leg.localStreamId,
          value: BigInt(reason),
          payload: Buffer.alloc(0),
        });
      }
    }
  }

  private unknownOrViolation(
    connection: FabricEndpointConnection,
    streamId: string,
  ): void {
    if (!connection.tombstones.has(streamId)) {
      this.reject(connection, streamId, FabricReset.UnknownStream);
      return;
    }
    this.strike(connection);
  }

  private reject(
    connection: FabricEndpointConnection,
    streamId: string,
    reason: FabricReset,
    countStrike = true,
  ): void {
    if (this.isCurrent(connection)) {
      connection.send({
        kind: FabricKind.Reset,
        streamId,
        value: BigInt(reason),
        payload: Buffer.alloc(0),
      });
    }
    this.remember(connection, streamId);
    if (countStrike) this.strike(connection);
  }

  private strike(connection: FabricEndpointConnection): void {
    connection.strikes += 1;
    if (connection.strikes < this.maxStrikes) return;
    this.unregister(connection, FabricReset.ProtocolViolation);
    connection.close(4400);
  }

  private allocateStreamId(connection: FabricEndpointConnection): string | null {
    this.pruneTombstones(connection);
    for (let attempt = 0; attempt < 32; attempt += 1) {
      const candidate = this.nextStreamId();
      if (
        candidate !== ZERO_STREAM_ID &&
        !connection.streams.has(candidate) &&
        !connection.pending.has(candidate) &&
        !connection.tombstones.has(candidate)
      ) {
        return candidate;
      }
    }
    return null;
  }

  private remember(connection: FabricEndpointConnection, streamId: string): void {
    connection.tombstones.set(streamId, this.now() + this.tombstoneMs);
    this.pruneTombstones(connection);
    while (connection.tombstones.size > this.maxTombstones) {
      const oldest = connection.tombstones.keys().next().value as string | undefined;
      if (!oldest) break;
      connection.tombstones.delete(oldest);
    }
  }

  private pruneTombstones(connection: FabricEndpointConnection): void {
    const now = this.now();
    for (const [streamId, expiresAt] of connection.tombstones) {
      if (expiresAt <= now) connection.tombstones.delete(streamId);
    }
  }

  private rememberRevocation(table: Map<string, number>, handle: string): void {
    // Delete first so refreshing an existing handle also refreshes its
    // insertion order for bounded eviction.
    table.delete(handle);
    table.set(handle, this.now() + this.revocationTombstoneMs);
    while (table.size > this.maxRevocationTombstones) {
      const oldest = table.keys().next().value as string | undefined;
      if (!oldest) break;
      table.delete(oldest);
    }
  }

  private pruneRevocations(): void {
    const now = this.now();
    for (const table of [this.revokedEndpoints, this.revokedRoutes]) {
      for (const [handle, expiresAt] of table) {
        if (expiresAt <= now) table.delete(handle);
      }
    }
  }

  private isCurrent(connection: FabricEndpointConnection): boolean {
    return (
      !connection.closed &&
      this.endpoints.get(connection.context.endpointHandle) === connection
    );
  }
}

function parseExpiry(value: string | null): number | null {
  if (value === null) return null;
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) ? parsed : null;
}
