// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type AgentInfo = { id: string, label: string, probe: ProbeState, capabilities: Capabilities, catalog: Catalog, 
/**
 * True for the agent shipped in the installer, which is preselected on
 * first run so a new user can run something immediately.
 */
builtin: boolean, };

export type AssetPreviewError = "notFound" | "forbidden" | "unsupported" | "tooLarge" | "sourceChanged";

export type AssetPreviewKind = "image" | "markdown" | "text" | "html" | "video";

export type AssetPreviewMetadata = { kind: AssetPreviewKind, mediaType: string, sourceBytes: number, 
/**
 * Stable enough to make a stale viewer response detectable without
 * exposing an operating-system path.
 */
version: string, };

export type AssetPreviewRequest = { source: WorkspaceFileSource, };

export type Attachment = { name: string, mime: string, path?: string, 
/**
 * Inline payload, base64. Only set for small pastes such as screenshots.
 */
dataBase64?: string, };

export type BlobKind = "reasoning" | "toolCall";

/**
 * One compact row in a batch. Full source content is fetched by `blob.get`.
 */
export type BlobOverview = { itemId: string, kind: BlobKind, overview: string, blob?: BlobRef, };

export type BlobPayload = { id: string, value: JsonValue, };

/**
 * A complete address for one stored blob: what it is, and where it sits.
 *
 * The locator travels with the reference on purpose (`docs/session-storage.md`
 * §3.3). A content id alone only narrows the search to one bucket file, which
 * is what made the old reader scan and deserialize a whole bucket per read;
 * carrying the byte range instead makes the row that holds the reference its
 * own index, so no separate blob index has to be built, loaded or kept honest.
 */
export type BlobRef = { 
/**
 * First 24 hex characters of the payload's SHA-256. 96 bits: collision
 * odds stay negligible at any session size, and every trunk row carries
 * one, so the 40 characters saved are not decorative.
 */
id: string, bytes: number, 
/**
 * `<bucket>:<offset>:<length>`. Opaque to clients — they hand it back
 * unchanged and the daemon resolves it against this session's own blob
 * files, verifying the id it finds there before answering.
 */
at: string, };

/**
 * What an agent can do, declared up front.
 *
 * The frontend renders controls from this rather than probing with calls that
 * might fail: a user should never be offered a model picker by an agent that
 * cannot switch models (`architecture.md` §3.2).
 */
export type Capabilities = { interrupt: boolean, setModel: boolean, 
/**
 * How hard the model should think. A separate switch from `set_model`
 * because it is a separate axis: the same model runs at any of its levels,
 * and which levels exist is the model's own business (`ModelInfo::efforts`).
 */
setEffort: boolean, setMode: boolean, permissions: boolean, 
/**
 * The agent can rehydrate a past session itself. When false the daemon
 * falls back to read-only replay from its own log.
 */
resume: boolean, 
/**
 * The Agent can create a genuinely independent context through a
 * completed turn. False means the UI keeps the action visible but honest.
 */
fork: boolean, attachments: boolean, };

export type Catalog = { models: Array<ModelInfo>, modes: Array<ModeInfo>, commands: Array<CommandInfo>, defaultModel?: string, defaultMode?: string, defaultEffort?: string, };

/**
 * A slash command the agent understands.
 *
 * Nothing about running one is special: it is sent as ordinary prompt text, and
 * the agent recognises its own commands. What the agent alone can supply is the
 * *list* — which for a Claude Code install is dozens of commands and skills that
 * are otherwise undiscoverable outside its own terminal UI.
 */
export type CommandInfo = { 
/**
 * Without the leading slash.
 */
name: string, description?: string, 
/**
 * What to type after the name, when it takes an argument — the agent's own
 * wording, e.g. `[low|medium|high]`.
 */
argumentHint?: string, };

/**
 * A client proving it is on the authorized list, without sending its secret.
 */
export type DeviceAuth = { deviceId: string, 
/**
 * Fresh per connection. A nonce is never accepted twice, so intercepting
 * one proof buys nothing.
 */
nonce: string, proof: string, };

/**
 * What a client keeps after redeeming an invite.
 */
export type DeviceCredential = { deviceId: string, 
/**
 * Stable machine identity. Device ids name one browser authorization and
 * must never be reused as a routing target.
 */
machineId: string, 
/**
 * Shared with this machine only. Never sent again after this reply: later
 * connections prove knowledge of it instead (`security-model.md` §4.2).
 */
secret: string, machineName: string, fingerprint: string, };

/**
 * One entry in the machine's authorized-devices list.
 */
export type DeviceInfo = { id: string, name: string, pairedAt: string, lastSeenAt?: string, 
/**
 * True while this device has a live connection to the machine.
 */
connected: boolean, 
/**
 * What this device may ask for. Absent from machines that predate grants,
 * where every authorized device could do everything.
 */
grants?: Array<string>, };

/**
 * A one-time chance to become an authorized device.
 *
 * The code is not a credential: it buys exactly one exchange, and only within
 * its lifetime. What comes back from that exchange is the credential.
 */
export type DeviceInvite = { code: string, 
/**
 * Where the client should meet this machine.
 *
 * Absent when remote access is off, and then there is nowhere to send
 * anyone: this machine does not know its own address on the network, so an
 * invite without this cannot be turned into a link. The workbench asks for
 * a relay first for that reason; privileged LAN transport is deliberately
 * unsupported.
 */
rendezvousUrl?: string, expiresAt: string, 
/**
 * What redeeming this invitation will be worth. Shown before anyone
 * accepts it, because a grant nobody was told about is not a choice.
 */
grants?: Array<string>, };

export type DirectoryEntry = { name: string, path: string, };

export type DirectoryListing = { path: string, parent: string | null, directories: Array<DirectoryEntry>, 
/**
 * Openable VS Code workspace definitions in this directory.
 */
workspaceFiles: Array<DirectoryEntry>, };

export type ErrorCode = "badRequest" | "unauthorized" | "notFound" | "conflict" | "unsupported" | "forbidden" | "internal" | "protocolVersion";

/**
 * The first encrypted record on a client-opened logical stream.
 */
export type ExchangeRequestHead = { version: number, method: string, metadata: JsonValue, bodyLength?: number, timeoutMs?: number, };

export type ExchangeResponseHead = { status: number, metadata: JsonValue, bodyLength?: number, error?: ProtocolError, };

export type FileNode = { name: string, 
/**
 * Workspace-relative, always forward-slashed so clients need no per-OS logic.
 */
path: string, isDir: boolean, size?: number, 
/**
 * Absent means "not expanded yet" rather than "empty".
 */
children?: Array<FileNode>, };

export type GitChange = { path: string, kind: GitChangeKind, staged: boolean, };

export type GitChangeKind = "added" | "modified" | "deleted" | "renamed" | "untracked";

export type GitStatus = { branch?: string, changes: Array<GitChange>, clean: boolean, };

export type HelloResult = { daemonVersion: string, protocolVersion: number, machineId: string, 
/**
 * Short human-comparable form of the daemon key, for out-of-band checking.
 */
fingerprint: string, transport: TransportKind, machineName: string, 
/**
 * Advertised inside the encrypted data plane. The viewer's local RTC
 * preference still decides whether negotiation is attempted.
 */
rtcSupported: boolean, };

/**
 * The ways back into an identity that has no password.
 *
 * A trial identity is reachable only through these, so whatever shows them
 * has one chance to do it: nothing on this machine keeps a copy, and the Hub
 * will not repeat itself.
 */
export type HubClaim = { 
/**
 * One-time link, good for opening this identity in another browser.
 */
claimUrl: string, 
/**
 * Present only when the identity was just created. Left out of the wire
 * rather than sent as null, so that the generated `recoveryKey?: string`
 * describes what actually arrives.
 */
recoveryKey?: string, expiresAt: string, };

/**
 * Another machine belonging to whoever owns this one.
 *
 * The Hub knows this list; nothing on this machine does. It is fetched
 * through the daemon rather than by the UI directly, and that is the whole
 * design: the client stays one program that talks to one daemon, and the
 * account remains something only the server side knows about.
 */
export type HubMachine = { 
/**
 * The Hub's id, which is also what `HubStatus::Paired` reports for this
 * machine — so a client can tell which entry is the one it is sitting on.
 */
id: string, 
/**
 * Stable daemon-owned handle used by Preview locators across clients.
 */
deviceHandle: string, name: string, online: boolean, fingerprint: string, lastSeenAt?: string, };

/**
 * Where this machine stands with a Hub.
 *
 * One shape covers every stage of pairing so the UI polls a single call and
 * renders from what it gets back, rather than tracking the flow itself and
 * getting out of step with the daemon after a restart.
 */
export type HubStatus = { "state": "unpaired" } | { "state": "pairing", hubUrl: string, userCode: string, verificationUri: string, 
/**
 * The same address with the code already filled in, for a QR code.
 */
verificationUriComplete: string, expiresAt: string, } | { "state": "paired", hubUrl: string, 
/**
 * The Hub's id for this machine, which is what the owner sees listed.
 */
machineId: string, 
/**
 * True while the outbound connection to the Hub is up. False means
 * remote access is down even though pairing is intact.
 */
online: boolean, } | { "state": "failed", hubUrl: string, message: string, };

/**
 * A one-time way to reach one of those machines through the forwarding layer.
 *
 * Spent by the connection that uses it, so a client that needs to reconnect
 * asks for another rather than replaying this one.
 */
export type HubTicket = { url: string, expiresAt: string, 
/**
 * Opaque name Relay carries to the target daemon in OPEN.
 */
channelCapability: string, 
/**
 * Per-connection E2E secret. Never placed in a URL or Relay API.
 */
channelSecret: string, 
/**
 * One-shot outer Fabric route. It contains no workspace/path/business data.
 */
fabricRouteTicket: string, fabricRouteExpiresAt: string, 
/**
 * The target machine's key fingerprint, learned from the Hub rather than
 * from the connection — which is what makes comparing the two worth
 * anything.
 */
fingerprint: string, };

export type InteractionAnswer = { questionId: string, selectedOptionIds: Array<string>, freeformText?: string, };

export type InteractionOption = { id: string, label: string, };

export type InteractionQuestion = { id: string, prompt: string, allowMultiple: boolean, allowFreeform: boolean, options: Array<InteractionOption>, };

/**
 * Proof of the PSK carried in the fragment half of a pairing link.
 */
export type InviteAuth = { inviteId: string, nonce: string, proof: string, };

/**
 * How much of a machine an invitation is worth.
 *
 * Its own type rather than a bare list of strings so that the request carrying
 * it can grow other limits — an expiry, a workspace — without changing shape
 * again.
 */
export type InviteScope = { grants: Array<string>, };

/**
 * Streaming increment for an item already on the timeline.
 *
 * Deltas are transport-only: they are never written to the session log, which
 * keeps file size proportional to final content rather than to token count.
 */
export type ItemDelta = { "kind": "text", delta: string, } | { "kind": "toolStatus", status: ToolStatus, detail?: ToolCallDetail, };

export type LogEntry = { name: string, 
/**
 * A number on the wire. Declared as one here too: the generated `bigint`
 * would be a type that never matches what `JSON.parse` actually produces.
 */
bytes: number, };

/**
 * The end of one log file, and where it came from.
 *
 * The path is included even though the text makes it redundant on the machine
 * itself: on the desktop it is what someone attaches to a bug report or opens in
 * an editor, and knowing which file they are reading matters when there are
 * several.
 */
export type LogTail = { name: string, path: string, text: string, 
/**
 * Every log in the directory, newest first, with its size in bytes.
 */
files: Array<LogEntry>, };

export type ModeInfo = { id: string, label: string, description?: string, };

export type ModelInfo = { id: string, label: string, contextWindow?: number, reasoning: boolean, 
/**
 * The thinking levels this model accepts, in the order it named them —
 * weakest first, because that is how a slider reads. Empty means this model
 * has no such dial, and the control belongs nowhere near it.
 */
efforts: Array<string>, };

export type NoticeLevel = "info" | "warning" | "error";

/**
 * How a peer proves possession of an end-to-end secret during carrier setup.
 *
 * Only a capability *name* is present for hosted sessions.  The daemon
 * redeems that name directly with Control; the Relay never receives the
 * secret.  Loopback uses the one-use proof delivered by the owner-only shell
 * as its short-lived PSK.
 */
export type PeerAuth = { "type": "loopback", context: string, nonce: string, proof: string, } | { "type": "device", deviceId: string, nonce: string, proof: string, } | { "type": "hosted", capabilityId: string, nonce: string, proof: string, } | { "type": "invite", inviteId: string, nonce: string, proof: string, };

export type PeerHello = { version: number, clientName: string, auth: PeerAuth, 
/**
 * Capability advertisement only.  Signaling remains encrypted data-plane
 * traffic and no RTC address is ever placed in this hello.
 */
rtcSupported: boolean, };

export type PeerWelcome = { version: number, serverNonce: string, proof: string, };

export type PermissionOption = { id: string, label: string, kind: PermissionOptionKind, };

export type PermissionOptionKind = "allowOnce" | "allowAlways" | "reject";

export type PermissionOutcome = { "outcome": "selected", optionId: string, } | { "outcome": "answered", answers: Array<InteractionAnswer>, } | { "outcome": "timedOut", appliedDefault: string, } | { "outcome": "canceled" };

export type PermissionRequest = { id: string, 
/**
 * Permissions resume with elevated authority; questions resume with the
 * selected answer but keep the session's chosen permission mode.
 */
kind: PermissionRequestKind, title: string, detail?: string, 
/**
 * The tool call this approval gates, when it gates one.
 */
toolCallId?: string, options: Array<PermissionOption>, 
/**
 * Structured questions carried by Agent-native interaction tools. Empty
 * for the original one-row approval card, so older stored sessions keep
 * their exact behaviour.
 */
questions?: Array<InteractionQuestion>, };

export type PermissionRequestKind = "permission" | "question" | "planApproval";

export type ProbeState = { "state": "ready" } | { "state": "notInstalled" } | { "state": "unavailable", reason: string, };

export type ProtocolError = { code: ErrorCode, message: string, };

/**
 * A provider's configuration, minus the secret.
 *
 * `hasApiKey` rather than the key itself: the UI only needs to know whether
 * to show "configured" or an empty field, and sending the value back would
 * put it in every client's memory for no gain.
 */
export type ProviderInfo = { id: string, hasApiKey: boolean, 
/**
 * The address in use, whether the user typed it or we ship it. Filled in
 * even when they typed nothing, so the page shows where their key is going.
 */
baseUrl?: string, label: string, 
/**
 * `openai` | `anthropic`.
 */
dialect: string, 
/**
 * True for a provider the user added, which is also the only kind that can
 * be removed again.
 */
custom: boolean, 
/**
 * The models this key can use, as the provider itself reported them — or
 * the list the user wrote by hand.
 */
models: Array<string>, 
/**
 * Why `models` is empty, in the provider's own words. The alternative is a
 * picker that is empty for no stated reason, which sends people to the
 * wrong place: a rejected key looks exactly like a bug in the app.
 */
problem?: string, };

/**
 * Whether this machine is reachable through a rendezvous relay.
 */
export type RemoteAccess = { relayUrl?: string, 
/**
 * Where clients meet this machine. Unguessable, and derived from the
 * machine identity so it survives restarts.
 */
rendezvousUrl?: string, online: boolean, };

/**
 * Successful payloads, one per request that returns something.
 */
export type Reply = { "type": "hello", "data": HelloResult } | { "type": "subscribed", "data": { snapshot: SessionSnapshot, replayed: Array<SequencedEvent>, 
/**
 * True when the requested `sinceSeq` fell outside the retained window
 * and the snapshot is a full reset rather than a continuation.
 */
reset: boolean, } } | { "type": "agents", "data": Array<AgentInfo> } | { "type": "hubStatus", "data": HubStatus } | { "type": "hubClaim", "data": { status: HubStatus, claim: HubClaim, } } | { "type": "hubMachines", "data": Array<HubMachine> } | { "type": "hubTicket", "data": HubTicket } | { "type": "devices", "data": { devices: Array<DeviceInfo>, remote: RemoteAccess, } } | { "type": "invite", "data": DeviceInvite } | { "type": "claimed", "data": DeviceCredential } | { "type": "remoteAccess", "data": RemoteAccess } | { "type": "settings", "data": Settings } | { "type": "log", "data": LogTail } | { "type": "update", "data": UpdateStatus } | { "type": "updateDownload", "data": UpdateDownload } | { "type": "session", "data": SessionSummary } | { "type": "sessions", "data": Array<SessionSummary> } | { "type": "snapshot", "data": SessionSnapshot } | { "type": "roundLayer", "data": RoundLayer } | { "type": "roundTrunk", "data": RoundTrunk } | { "type": "blob", "data": BlobPayload } | { "type": "workspace", "data": WorkspaceInfo } | { "type": "workspaces", "data": Array<WorkspaceInfo> } | { "type": "directory", "data": DirectoryListing } | { "type": "fileTree", "data": FileNode } | { "type": "gitStatus", "data": GitStatus } | { "type": "gitDiff", "data": { diff: string, } } | { "type": "gitCommit", "data": { commit: string, } } | { "type": "pty", "data": { ptyId: string, } } | { "type": "ack" };

export type Request = { "type": "connection.identity" } | { "type": "subscribe", "payload": { sessionId: string, sinceSeq: number, 
/**
 * Prefetches the last round's trunk index and final trunk details in
 * the subscription response.
 */
expandLastRound: boolean, } } | { "type": "unsubscribe", "payload": { sessionId: string, } } | { "type": "agent.list" } | { "type": "agent.refresh" } | { "type": "session.create", "payload": { workspaceId: string, agentId: string, modelId: string | null, modeId: string | null, title: string | null, 
/**
 * Where the agent starts, inside the workspace. Absent means the
 * workspace root, which is what every client sent before this field
 * existed. Relative paths resolve against the root; an absolute path
 * must still fall inside it, and the daemon refuses the rest rather
 * than clamping — a task silently run in the wrong directory is worse
 * than one that refused to start.
 */
cwd: string | null, } } | { "type": "session.list", "payload": { workspaceId: string | null, includeArchived: boolean, } } | { "type": "session.get", "payload": { sessionId: string, } } | { "type": "round.trunk.list", "payload": { sessionId: string, roundId: string, cursor: string | null, limit: number | null, } } | { "type": "round.trunk.get", "payload": { sessionId: string, roundId: string, trunkIndex: number, } } | { "type": "blob.get", "payload": { sessionId: string, blob: BlobRef, } } | { "type": "session.send", "payload": { sessionId: string, text: string, attachments: Array<Attachment>, 
/**
 * Deprecated wire field. Current clients always send `null`; Preview
 * locators are rebound in the workbench from relative/absolute paths.
 * Kept so older clients remain deserializable.
 */
artifactPreviewBaseUrl: string | null, 
/**
 * Browser-composed, deployment-aware Asset Preview prefix for this
 * session's workspace. It is context, not authority: opening a link
 * still performs normal target selection, authentication and E2EE.
 * The daemon validates the URL shape and turns it into fixed Agent
 * guidance; arbitrary client-authored system prompts are never accepted.
 */
artifactPreviewBaseUrl: string | null, 
/**
 * Claims this message as a continuation of a round left open by an
 * interrupt, rather than a new one. Only interrupts need this: the
 * daemon auto-stitches approval and guidance continuations on its
 * own, because those are unambiguous (`docs/architecture.md`'s
 * analysis substrate proposal §3.2). Absent, unknown, or naming a
 * round that already ended, this is treated as a new round — a
 * wrong stitch is a worse failure than an extra round.
 */
continuesRound: string | null, } } | { "type": "session.fork", "payload": { sessionId: string, turnId: string, } } | { "type": "session.interrupt", "payload": { sessionId: string, } } | { "type": "session.close", "payload": { sessionId: string, } } | { "type": "session.archive", "payload": { sessionId: string, archived: boolean, } } | { "type": "session.rename", "payload": { sessionId: string, title: string, } } | { "type": "session.delete", "payload": { sessionId: string, } } | { "type": "session.setModel", "payload": { sessionId: string, modelId: string, } } | { "type": "session.setMode", "payload": { sessionId: string, modeId: string, } } | { "type": "session.setEffort", "payload": { sessionId: string, effortId: string, } } | { "type": "session.respondPermission", "payload": { sessionId: string, requestId: string, outcome: PermissionOutcome, } } | { "type": "settings.get" } | { "type": "settings.setProvider", "payload": { providerId: string, 
/**
 * `None` leaves the stored key alone; an empty string clears it.
 */
apiKey: string | null, baseUrl: string | null, 
/**
 * What to call it on screen, for a provider the user is adding.
 */
label: string | null, 
/**
 * `openai` | `anthropic`, when the address does not belong to a
 * provider we already know the shape of.
 */
dialect: string | null, 
/**
 * Models by hand, for an endpoint that cannot list its own.
 */
models: Array<string> | null, } } | { "type": "settings.forgetProvider", "payload": { providerId: string, } } | { "type": "log.tail", "payload": { 
/**
 * Omitted means the daemon's own log, which is what an error is about
 * almost every time.
 */
name: string | null, } } | { "type": "update.check" } | { "type": "update.download" } | { "type": "update.downloadState" } | { "type": "update.dismiss" } | { "type": "hub.status" } | { "type": "hub.pair", "payload": { hubUrl: string, displayName: string | null, } } | { "type": "hub.trial", "payload": { hubUrl: string, displayName: string | null, } } | { "type": "hub.claimLink" } | { "type": "hub.machines" } | { "type": "hub.connect", "payload": { machineId: string, } } | { "type": "hub.unpair" } | { "type": "device.list" } | { "type": "device.invite", "payload": InviteScope | null } | { "type": "device.claim", "payload": { code: string, deviceName: string, } } | { "type": "device.revoke", "payload": { deviceId: string, } } | { "type": "device.remoteAttach", "payload": { relayUrl: string, joinToken: string | null, } } | { "type": "device.remoteDetach" } | { "type": "workspace.list" } | { "type": "workspace.open", "payload": { root: string, } } | { "type": "workspace.create", "payload": { root: string, name: string, } } | { "type": "workspace.rename", "payload": { workspaceId: string, name: string, } } | { "type": "workspace.remove", "payload": { workspaceId: string, } } | { "type": "directory.list", "payload": { path: string | null, } } | { "type": "file.tree", "payload": { workspaceId: string, path: string | null, depth: number | null, } } | { "type": "file.write", "payload": { workspaceId: string, path: string, content: string, } } | { "type": "git.status", "payload": { workspaceId: string, } } | { "type": "git.diff", "payload": { workspaceId: string, path: string | null, } } | { "type": "git.commit", "payload": { workspaceId: string, message: string, 
/**
 * Empty means "everything currently changed".
 */
paths: Array<string>, } } | { "type": "pty.open", "payload": { workspaceId: string, cols: number | null, rows: number | null, } } | { "type": "pty.write", "payload": { ptyId: string, data: string, } } | { "type": "pty.resize", "payload": { ptyId: string, cols: number, rows: number, } } | { "type": "pty.close", "payload": { ptyId: string, } };

export type RoundBatch = { summary: RoundBatchSummary, 
/**
 * Full process narration for this batch. It belongs to the expanded trunk,
 * not to the session narrative. A compact prefix remains in `summary.text`.
 */
monologue?: string, blobs: Array<BlobOverview>, };

/**
 * A semantic group inside a trunk: one monologue and the work following it,
 * bounded to sixteen blobs even when an agent never narrates.
 */
export type RoundBatchSummary = { index: number, firstItemId: string, blobCount: number, text: string, };

/**
 * A page of visible trunks in one round. `nextCursor` asks for the preceding
 * page; cursors are opaque to clients.
 */
export type RoundLayer = { round: RoundSummary, trunks: Array<RoundTrunkSummary>, nextCursor?: string, expandedTrunk?: RoundTrunk, };

export type RoundLayerOutcome = "completed" | "failed" | "canceled" | "superseded" | "running";

/**
 * Compact session-layer description of one user request.
 */
export type RoundSummary = { roundId: string, userItemId?: string, startedAtMs: number, endedAtMs: number, outcome: RoundLayerOutcome, trunkCount: number, };

export type RoundTrunk = { summary: RoundTrunkSummary, batches: Array<RoundBatch>, };

/**
 * A visible, bounded section of a round. Trunks are carried by the round
 * protocol layer; they are not a fourth storage/addressing layer.
 */
export type RoundTrunkSummary = { index: number, firstItemId: string, blobCount: number, title: string, batches: Array<RoundBatchSummary>, };

/**
 * Non-trickle RTC signaling carried inside an already E2EE Exchange.
 */
export type RtcNegotiationRequest = { sdp: string, };

export type RtcNegotiationResponse = { sdp: string, capabilityId: string, secret: string, };

export type SearchMatch = { path: string, line?: number, preview: string, };

/**
 * A sequenced event as delivered to clients.
 *
 * The sequence number is what makes gap-free reconnect possible: clients send
 * back the last `seq` they saw and the daemon replays from there.
 */
export type SequencedEvent = { seq: number, sessionId: string, event: SessionEvent, };

/**
 * Anything the daemon sends to a client.
 */
export type ServerFrame = { "type": "event", topic: string, payload: SequencedEvent, } | { "type": "pty", ptyId: string, data: string, } | { "type": "ptyClosed", ptyId: string, exitCode?: number, } | { "type": "notice", level: NoticeLevel, message: string, } | { "type": "updateDownload", download: UpdateDownload, } | { "type": "desync", sessionId: string, missed: number, };

export type SessionEvent = { "type": "turnStarted", turnId: string, 
/**
 * Zero is accepted from adapters; the session boundary replaces it
 * with its own wall clock before the event reaches a client.
 */
startedAtMs: number, } | { "type": "item", turnId: string, item: TimelineItem, } | { "type": "itemDelta", turnId: string, itemId: string, delta: ItemDelta, } | { "type": "turnCompleted", turnId: string, usage: Usage, forkCheckpoint?: string, } | { "type": "turnFailed", turnId: string, error: TurnError, } | { "type": "turnCanceled", turnId: string, } | { "type": "permissionRequested", request: PermissionRequest, } | { "type": "permissionResolved", requestId: string, outcome: PermissionOutcome, } | { "type": "modelChanged", modelId: string, } | { "type": "modeChanged", modeId: string, } | { "type": "effortChanged", effortId: string, } | { "type": "titleChanged", title: string, } | { "type": "sessionStatusChanged", status: SessionStatus, };

/**
 * Everything a client needs to render a session from scratch.
 */
export type SessionSnapshot = { summary: SessionSummary, items: Array<TimelineItem>, 
/**
 * Sequence number this snapshot is current as of. Events with a lower or
 * equal seq have already been folded in.
 */
seq: number, pendingPermissions: Array<PermissionRequest>, 
/**
 * One entry per user request. `items` carries only the session narrative;
 * tool calls and reasoning are addressed through the round layer instead
 * of being replayed wholesale (`docs/session-storage.md`).
 */
rounds?: Array<RoundSummary>, 
/**
 * The last round's recent trunk index and last trunk details, prefetched
 * in the same response for the unread/mobile-first-screen path.
 */
expandedRound?: RoundLayer, };

export type SessionStatus = "idle" | "running" | "waiting" | "readOnly" | "failed" | "closed";

export type SessionSummary = { id: string, workspaceId: string, agentId: string, 
/**
 * Absent until the session has been named — by the user, or by the daemon
 * from the first thing they said. Clients supply their own placeholder;
 * the daemon has no business picking a word in the user's language.
 */
title?: string, status: SessionStatus, modelId?: string, modeId?: string, effortId?: string, createdAtMs: number, updatedAtMs: number, archived: boolean, 
/**
 * Set when this session cannot be opened here. It is still listed: the
 * conversation is in the user's own project folder, and an unexplained
 * absence is worse than a row that says why it is out of reach.
 */
unsupported?: UnsupportedFormat, };

/**
 * The machine-level settings a client may see and change.
 */
export type Settings = { providers: Array<ProviderInfo>, 
/**
 * Whether the daemon accepts connections from the local network.
 */
lanEnabled: boolean, };

/**
 * One entry in a session's timeline.
 *
 * `id` is assigned by the daemon, not the agent, so that deltas can address an
 * item regardless of whether the underlying agent has a concept of message ids.
 */
export type TimelineItem = { "type": "userMessage", id: string, text: string, attachments: Array<Attachment>, } | { "type": "assistantMessage", id: string, text: string, } | { "type": "reasoning", id: string, text: string, } | { "type": "toolCall", id: string, name: string, status: ToolStatus, detail: ToolCallDetail, } | { "type": "todo", id: string, items: Array<TodoEntry>, } | { "type": "compaction", id: string, reason: string, } | { "type": "error", id: string, message: string, } | { "type": "turnSummary", id: string, stats: TurnStats, };

export type TodoEntry = { text: string, status: TodoStatus, };

export type TodoStatus = "pending" | "inProgress" | "completed" | "cancelled";

/**
 * Which renderer the frontend should reach for.
 *
 * Adapters map their agent's tool names onto these variants. The mapping table
 * lives inside each adapter on purpose: a single global table would become a
 * coupling point between every adapter we ever add.
 */
export type ToolCallDetail = { "kind": "overview", toolKind: ToolKind, overview: string, input: string, output: string, } | { "kind": "shell", command: string, output: string, exitCode?: number, } | { "kind": "read", path: string, content: string, truncated: boolean, } | { "kind": "edit", path: string, diff: string, } | { "kind": "write", path: string, content: string, } | { "kind": "search", query: string, matches: Array<SearchMatch>, } | { "kind": "fetch", url: string, summary: string, } | { "kind": "plan", markdown: string, } | { "kind": "subAgent", agent: string, prompt: string, items: Array<TimelineItem>, } | { "kind": "unknown", raw: JsonValue, };

/**
 * A stable semantic category shared by every Agent adapter.
 *
 * Tool names are Agent-specific (`Bash`, `commandExecution`, `execute`), while
 * the activity icon should mean the same thing everywhere.
 */
export type ToolKind = "shell" | "read" | "write" | "edit" | "search" | "fetch" | "plan" | "subAgent" | "mcp" | "other";

export type ToolStatus = "pending" | "running" | "ok" | "error" | "canceled";

/**
 * How this client reached the daemon. Surfaced so the UI can show the user
 * which of the three paths in `architecture.md` §1 is in use.
 */
export type TransportKind = "loopback" | "lan" | "forwarded";

export type TurnError = { code: TurnErrorCode, 
/**
 * Already user-facing. §4.4 of `docs/testing.md` requires every failure
 * mode to surface something actionable rather than a blank screen.
 */
message: string, };

export type TurnErrorCode = "missingCredentials" | "rateLimited" | "upstream" | "timeout" | "agentCrashed" | "canceled" | "internal";

export type TurnOutcome = "completed" | "failed" | "canceled";

/**
 * Metrics retained with the turn rather than only with the latest event.
 */
export type TurnStats = { turnId: string, outcome: TurnOutcome, startedAtMs: number, finishedAtMs: number, durationMs: number, usage: Usage, toolCalls: number, 
/**
 * Opaque Agent checkpoint used only when that Agent supports true forks.
 */
forkCheckpoint?: string, };

/**
 * A session written by a newer build than this one.
 *
 * Both numbers travel so a client can tell the user which side is behind
 * without knowing anything about storage layouts itself.
 */
export type UnsupportedFormat = { written: number, supported: number, };

/**
 * How far the machine has got fetching the installer it was asked to fetch.
 *
 * A state rather than a reply to one call, because a download outlives the
 * click that started it: the window can be closed, the workbench reloaded, a
 * second client opened on a phone, and all of them have to see the same thing.
 * The machine is the one place that knows, so it is the one place that says.
 *
 * Fetching is separate from installing on purpose. What ends this is a file on
 * disk and a sentence on screen; the installer stops the daemon and every agent
 * mid-turn, so when to pay that is the user's call.
 */
export type UpdateDownload = { "state": "idle" } | { "state": "fetching", version: string, 
/**
 * Bytes on disk so far. A number on the wire, so declared as one here:
 * the generated `bigint` would describe a value `JSON.parse` never
 * produces.
 */
received: number, 
/**
 * What the release host said the whole file weighs, when it said. A
 * server that sends no length is unusual but allowed, and a progress
 * bar that invents a total is worse than a byte count that does not.
 */
total?: number, } | { "state": "ready", version: string, 
/**
 * Where it landed. Only a shell running on this machine can do
 * anything with it; a browser on a phone shows the sentence and no
 * button.
 */
path: string, } | { "state": "failed", version: string, message: string, };

/**
 * Whether a newer build has been published, and where a person gets it.
 *
 * Asked for, never volunteered. A machine that promises to keep to itself has no
 * business making an outbound call nobody requested, and the answer is only
 * wanted at the moment someone wonders — which is why this is a menu item and a
 * button rather than a heartbeat.
 *
 * Nothing here *installs* anything either. The machine can fetch the installer
 * once asked (`UpdateDownload`), but running it — which stops the daemon and
 * whatever an agent was mid-turn — stays a click the user makes, not a timer we
 * fire.
 */
export type UpdateStatus = { 
/**
 * What this machine is running.
 */
current: string, 
/**
 * The newest published version, when the check got an answer at all.
 *
 * Left out of the wire rather than sent as null, here and below, so that the
 * generated `latest?: string` describes what actually arrives.
 */
latest?: string, 
/**
 * True only when `latest` is genuinely later. A build from source can be
 * ahead of the newest release, and telling that person to upgrade would be
 * telling them to go backwards.
 */
newer: boolean, 
/**
 * The release page: notes and checksums. Optional next to `download_url`,
 * because some people want to read before they fetch.
 */
url?: string, 
/**
 * The installer for *this* machine, when the manifest named one.
 *
 * Separate from `url` on purpose: the page is for a person, the file is for
 * a download button that must not open a browser just to fetch a binary.
 */
downloadUrl?: string, 
/**
 * Why there is no answer, in the words of whatever failed. The one outcome
 * worth refusing to render is a check that quietly says "up to date" after
 * reaching nothing at all.
 */
problem?: string, };

export type Usage = { inputTokens: number, outputTokens: number, cacheReadTokens: number, cacheWriteTokens: number, costUsd?: number, };

export type WorkspaceFileSource = { kind: WorkspaceFileSourceKind, workspaceHandle: string, path: string, };

export type WorkspaceFileSourceKind = "workspaceFile";

export type WorkspaceFolderInfo = { 
/**
 * Explorer label from `.code-workspace#folders[].name`, or the directory name.
 */
name: string, 
/**
 * Absolute path on the owning device. It never leaves the E2EE application channel.
 */
root: string, 
/**
 * Stable device-local locator for this physical root. Display names and
 * project membership never participate in resource identity.
 */
rootHandle: string, };

export type WorkspaceInfo = { id: string, name: string, 
/**
 * The first folder and Agent working directory.
 */
root: string, isGitRepo: boolean, folders: Array<WorkspaceFolderInfo>, workspaceFile?: string, };
