// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type AgentInfo = { id: string, label: string, probe: ProbeState, capabilities: Capabilities, catalog: Catalog, 
/**
 * True for the agent shipped in the installer, which is preselected on
 * first run so a new user can run something immediately.
 */
builtin: boolean, };

export type Attachment = { name: string, mime: string, path?: string, 
/**
 * Inline payload, base64. Only set for small pastes such as screenshots.
 */
dataBase64?: string, };

/**
 * What an agent can do, declared up front.
 *
 * The frontend renders controls from this rather than probing with calls that
 * might fail: a user should never be offered a model picker by an agent that
 * cannot switch models (`architecture.md` §3.2).
 */
export type Capabilities = { interrupt: boolean, setModel: boolean, setMode: boolean, permissions: boolean, 
/**
 * The agent can rehydrate a past session itself. When false the daemon
 * falls back to read-only replay from its own log.
 */
resume: boolean, attachments: boolean, };

export type Catalog = { models: Array<ModelInfo>, modes: Array<ModeInfo>, defaultModel?: string, defaultMode?: string, };

/**
 * A request as it arrives on the wire: an envelope id plus the request body.
 */
export type ClientEnvelope = { id: string, } & ({ "type": "hello", "payload": { clientName: string, protocolVersion: number, 
/**
 * Present when the client holds a device credential for this machine.
 * Required on forwarded connections: the machine decides admission
 * itself, and a relay vouches for nobody.
 */
device: DeviceAuth | null, } } | { "type": "subscribe", "payload": { sessionId: string, sinceSeq: number, } } | { "type": "unsubscribe", "payload": { sessionId: string, } } | { "type": "agent.list" } | { "type": "agent.refresh" } | { "type": "session.create", "payload": { workspaceId: string, agentId: string, modelId: string | null, modeId: string | null, title: string | null, } } | { "type": "session.list", "payload": { workspaceId: string | null, includeArchived: boolean, } } | { "type": "session.get", "payload": { sessionId: string, } } | { "type": "session.send", "payload": { sessionId: string, text: string, attachments: Array<Attachment>, } } | { "type": "session.interrupt", "payload": { sessionId: string, } } | { "type": "session.close", "payload": { sessionId: string, } } | { "type": "session.archive", "payload": { sessionId: string, archived: boolean, } } | { "type": "session.setModel", "payload": { sessionId: string, modelId: string, } } | { "type": "session.setMode", "payload": { sessionId: string, modeId: string, } } | { "type": "session.respondPermission", "payload": { sessionId: string, requestId: string, outcome: PermissionOutcome, } } | { "type": "settings.get" } | { "type": "settings.setProvider", "payload": { providerId: string, 
/**
 * `None` leaves the stored key alone; an empty string clears it.
 */
apiKey: string | null, baseUrl: string | null, } } | { "type": "hub.status" } | { "type": "hub.pair", "payload": { hubUrl: string, displayName: string | null, } } | { "type": "hub.trial", "payload": { hubUrl: string, displayName: string | null, } } | { "type": "hub.claimLink" } | { "type": "hub.unpair" } | { "type": "device.list" } | { "type": "device.invite", "payload": { name: string | null, } } | { "type": "device.claim", "payload": { code: string, deviceName: string, nonce: string, proof: string, } } | { "type": "device.revoke", "payload": { deviceId: string, } } | { "type": "device.remoteAttach", "payload": { relayUrl: string, joinToken: string | null, } } | { "type": "device.remoteDetach" } | { "type": "workspace.list" } | { "type": "workspace.open", "payload": { root: string, } } | { "type": "workspace.create", "payload": { root: string, name: string, } } | { "type": "file.tree", "payload": { workspaceId: string, path: string | null, depth: number | null, } } | { "type": "file.read", "payload": { workspaceId: string, path: string, } } | { "type": "file.write", "payload": { workspaceId: string, path: string, content: string, } } | { "type": "git.status", "payload": { workspaceId: string, } } | { "type": "git.diff", "payload": { workspaceId: string, path: string | null, } } | { "type": "git.commit", "payload": { workspaceId: string, message: string, 
/**
 * Empty means "everything currently changed".
 */
paths: Array<string>, } } | { "type": "pty.open", "payload": { workspaceId: string, cols: number | null, rows: number | null, } } | { "type": "pty.write", "payload": { ptyId: string, data: string, } } | { "type": "pty.resize", "payload": { ptyId: string, cols: number, rows: number, } } | { "type": "pty.close", "payload": { ptyId: string, } });

/**
 * A client proving it is on the authorized list, without sending its secret.
 */
export type DeviceAuth = { deviceId: string, 
/**
 * Fresh per connection. A nonce is never accepted twice, so intercepting
 * one proof buys nothing.
 */
nonce: string, proof: string, };

/**
 * What a client keeps after redeeming an invite.
 */
export type DeviceCredential = { deviceId: string, 
/**
 * Shared with this machine only. Never sent again after this reply: later
 * connections prove knowledge of it instead (`security-model.md` §4.2).
 */
secret: string, machineName: string, fingerprint: string, 
/**
 * The machine's half of the mutual proof, over the nonce the client sent.
 */
proof: string, };

/**
 * One entry in the machine's authorized-devices list.
 */
export type DeviceInfo = { id: string, name: string, pairedAt: string, lastSeenAt?: string, 
/**
 * True while this device has a live connection to the machine.
 */
connected: boolean, };

/**
 * A one-time chance to become an authorized device.
 *
 * The code is not a credential: it buys exactly one exchange, and only within
 * its lifetime. What comes back from that exchange is the credential.
 */
export type DeviceInvite = { code: string, 
/**
 * Where the client should meet this machine. Absent when remote access is
 * off, in which case the invite is only usable over the LAN.
 */
rendezvousUrl?: string, expiresAt: string, };

export type ErrorCode = "badRequest" | "unauthorized" | "notFound" | "conflict" | "unsupported" | "forbidden" | "internal" | "protocolVersion";

export type FileContent = { path: string, content: string, truncated: boolean, 
/**
 * False when the file looked binary; `content` is then a placeholder.
 */
isText: boolean, };

export type FileNode = { name: string, 
/**
 * Workspace-relative, always forward-slashed so clients need no per-OS logic.
 */
path: string, isDir: boolean, size?: number, 
/**
 * Absent means "not expanded yet" rather than "empty".
 */
children?: Array<FileNode>, };

export type GitChange = { path: string, kind: GitChangeKind, staged: boolean, };

export type GitChangeKind = "added" | "modified" | "deleted" | "renamed" | "untracked";

export type GitStatus = { branch?: string, changes: Array<GitChange>, clean: boolean, };

export type HelloResult = { daemonVersion: string, protocolVersion: number, machineId: string, 
/**
 * Short human-comparable form of the daemon key, for out-of-band checking.
 */
fingerprint: string, transport: TransportKind, machineName: string, 
/**
 * The machine's half of the mutual proof, present when the client
 * authenticated with a device credential. A client that asked for one and
 * did not get it is talking to something that is not its machine.
 */
proof?: string, };

/**
 * The ways back into an identity that has no password.
 *
 * A trial identity is reachable only through these, so whatever shows them
 * has one chance to do it: nothing on this machine keeps a copy, and the Hub
 * will not repeat itself.
 */
export type HubClaim = { 
/**
 * One-time link, good for opening this identity in another browser.
 */
claimUrl: string, 
/**
 * Present only when the identity was just created.
 */
recoveryKey?: string, expiresAt: string, };

/**
 * Where this machine stands with a Hub.
 *
 * One shape covers every stage of pairing so the UI polls a single call and
 * renders from what it gets back, rather than tracking the flow itself and
 * getting out of step with the daemon after a restart.
 */
export type HubStatus = { "state": "unpaired" } | { "state": "pairing", hubUrl: string, userCode: string, verificationUri: string, 
/**
 * The same address with the code already filled in, for a QR code.
 */
verificationUriComplete: string, expiresAt: string, } | { "state": "paired", hubUrl: string, 
/**
 * The Hub's id for this machine, which is what the owner sees listed.
 */
machineId: string, 
/**
 * True while the outbound connection to the Hub is up. False means
 * remote access is down even though pairing is intact.
 */
online: boolean, } | { "state": "failed", hubUrl: string, message: string, };

/**
 * Streaming increment for an item already on the timeline.
 *
 * Deltas are transport-only: they are never written to the session log, which
 * keeps file size proportional to final content rather than to token count.
 */
export type ItemDelta = { "kind": "text", delta: string, } | { "kind": "toolStatus", status: ToolStatus, detail?: ToolCallDetail, };

export type ModeInfo = { id: string, label: string, description?: string, };

export type ModelInfo = { id: string, label: string, contextWindow?: number, reasoning: boolean, };

export type NoticeLevel = "info" | "warning" | "error";

export type PermissionOption = { id: string, label: string, kind: PermissionOptionKind, };

export type PermissionOptionKind = "allowOnce" | "allowAlways" | "reject";

export type PermissionOutcome = { "outcome": "selected", optionId: string, } | { "outcome": "timedOut", appliedDefault: string, } | { "outcome": "canceled" };

export type PermissionRequest = { id: string, title: string, detail?: string, 
/**
 * The tool call this approval gates, when it gates one.
 */
toolCallId?: string, options: Array<PermissionOption>, };

export type ProbeState = { "state": "ready" } | { "state": "notInstalled" } | { "state": "unavailable", reason: string, };

export type ProtocolError = { code: ErrorCode, message: string, };

/**
 * A provider's configuration, minus the secret.
 *
 * `hasApiKey` rather than the key itself: the UI only needs to know whether
 * to show "configured" or an empty field, and sending the value back would
 * put it in every client's memory for no gain.
 */
export type ProviderInfo = { id: string, hasApiKey: boolean, baseUrl?: string, };

/**
 * Whether this machine is reachable through a rendezvous relay.
 */
export type RemoteAccess = { relayUrl?: string, 
/**
 * Where clients meet this machine. Unguessable, and derived from the
 * machine identity so it survives restarts.
 */
rendezvousUrl?: string, online: boolean, };

/**
 * Successful payloads, one per request that returns something.
 */
export type Reply = { "type": "hello", "data": HelloResult } | { "type": "subscribed", "data": { snapshot: SessionSnapshot, replayed: Array<SequencedEvent>, 
/**
 * True when the requested `sinceSeq` fell outside the retained window
 * and the snapshot is a full reset rather than a continuation.
 */
reset: boolean, } } | { "type": "agents", "data": Array<AgentInfo> } | { "type": "hubStatus", "data": HubStatus } | { "type": "hubClaim", "data": { status: HubStatus, claim: HubClaim, } } | { "type": "devices", "data": { devices: Array<DeviceInfo>, remote: RemoteAccess, } } | { "type": "invite", "data": DeviceInvite } | { "type": "claimed", "data": DeviceCredential } | { "type": "remoteAccess", "data": RemoteAccess } | { "type": "settings", "data": Settings } | { "type": "session", "data": SessionSummary } | { "type": "sessions", "data": Array<SessionSummary> } | { "type": "snapshot", "data": SessionSnapshot } | { "type": "workspace", "data": WorkspaceInfo } | { "type": "workspaces", "data": Array<WorkspaceInfo> } | { "type": "fileTree", "data": FileNode } | { "type": "fileContent", "data": FileContent } | { "type": "gitStatus", "data": GitStatus } | { "type": "gitDiff", "data": { diff: string, } } | { "type": "gitCommit", "data": { commit: string, } } | { "type": "pty", "data": { ptyId: string, } } | { "type": "ack" };

export type Request = { "type": "hello", "payload": { clientName: string, protocolVersion: number, 
/**
 * Present when the client holds a device credential for this machine.
 * Required on forwarded connections: the machine decides admission
 * itself, and a relay vouches for nobody.
 */
device: DeviceAuth | null, } } | { "type": "subscribe", "payload": { sessionId: string, sinceSeq: number, } } | { "type": "unsubscribe", "payload": { sessionId: string, } } | { "type": "agent.list" } | { "type": "agent.refresh" } | { "type": "session.create", "payload": { workspaceId: string, agentId: string, modelId: string | null, modeId: string | null, title: string | null, } } | { "type": "session.list", "payload": { workspaceId: string | null, includeArchived: boolean, } } | { "type": "session.get", "payload": { sessionId: string, } } | { "type": "session.send", "payload": { sessionId: string, text: string, attachments: Array<Attachment>, } } | { "type": "session.interrupt", "payload": { sessionId: string, } } | { "type": "session.close", "payload": { sessionId: string, } } | { "type": "session.archive", "payload": { sessionId: string, archived: boolean, } } | { "type": "session.setModel", "payload": { sessionId: string, modelId: string, } } | { "type": "session.setMode", "payload": { sessionId: string, modeId: string, } } | { "type": "session.respondPermission", "payload": { sessionId: string, requestId: string, outcome: PermissionOutcome, } } | { "type": "settings.get" } | { "type": "settings.setProvider", "payload": { providerId: string, 
/**
 * `None` leaves the stored key alone; an empty string clears it.
 */
apiKey: string | null, baseUrl: string | null, } } | { "type": "hub.status" } | { "type": "hub.pair", "payload": { hubUrl: string, displayName: string | null, } } | { "type": "hub.trial", "payload": { hubUrl: string, displayName: string | null, } } | { "type": "hub.claimLink" } | { "type": "hub.unpair" } | { "type": "device.list" } | { "type": "device.invite", "payload": { name: string | null, } } | { "type": "device.claim", "payload": { code: string, deviceName: string, nonce: string, proof: string, } } | { "type": "device.revoke", "payload": { deviceId: string, } } | { "type": "device.remoteAttach", "payload": { relayUrl: string, joinToken: string | null, } } | { "type": "device.remoteDetach" } | { "type": "workspace.list" } | { "type": "workspace.open", "payload": { root: string, } } | { "type": "workspace.create", "payload": { root: string, name: string, } } | { "type": "file.tree", "payload": { workspaceId: string, path: string | null, depth: number | null, } } | { "type": "file.read", "payload": { workspaceId: string, path: string, } } | { "type": "file.write", "payload": { workspaceId: string, path: string, content: string, } } | { "type": "git.status", "payload": { workspaceId: string, } } | { "type": "git.diff", "payload": { workspaceId: string, path: string | null, } } | { "type": "git.commit", "payload": { workspaceId: string, message: string, 
/**
 * Empty means "everything currently changed".
 */
paths: Array<string>, } } | { "type": "pty.open", "payload": { workspaceId: string, cols: number | null, rows: number | null, } } | { "type": "pty.write", "payload": { ptyId: string, data: string, } } | { "type": "pty.resize", "payload": { ptyId: string, cols: number, rows: number, } } | { "type": "pty.close", "payload": { ptyId: string, } };

export type SearchMatch = { path: string, line?: number, preview: string, };

/**
 * A sequenced event as delivered to clients.
 *
 * The sequence number is what makes gap-free reconnect possible: clients send
 * back the last `seq` they saw and the daemon replays from there.
 */
export type SequencedEvent = { seq: number, sessionId: string, event: SessionEvent, };

/**
 * Anything the daemon sends to a client.
 */
export type ServerFrame = { "type": "result", id: string, ok: boolean, payload?: Reply, error?: ProtocolError, } | { "type": "event", topic: string, payload: SequencedEvent, } | { "type": "pty", ptyId: string, data: string, } | { "type": "ptyClosed", ptyId: string, exitCode?: number, } | { "type": "notice", level: NoticeLevel, message: string, };

export type SessionEvent = { "type": "turnStarted", turnId: string, } | { "type": "item", turnId: string, item: TimelineItem, } | { "type": "itemDelta", turnId: string, itemId: string, delta: ItemDelta, } | { "type": "turnCompleted", turnId: string, usage: Usage, } | { "type": "turnFailed", turnId: string, error: TurnError, } | { "type": "turnCanceled", turnId: string, } | { "type": "permissionRequested", request: PermissionRequest, } | { "type": "permissionResolved", requestId: string, outcome: PermissionOutcome, } | { "type": "modelChanged", modelId: string, } | { "type": "modeChanged", modeId: string, } | { "type": "titleChanged", title: string, } | { "type": "sessionStatusChanged", status: SessionStatus, };

/**
 * Everything a client needs to render a session from scratch.
 */
export type SessionSnapshot = { summary: SessionSummary, items: Array<TimelineItem>, 
/**
 * Sequence number this snapshot is current as of. Events with a lower or
 * equal seq have already been folded in.
 */
seq: number, pendingPermissions: Array<PermissionRequest>, };

export type SessionStatus = "idle" | "running" | "readOnly" | "failed" | "closed";

export type SessionSummary = { id: string, workspaceId: string, agentId: string, 
/**
 * Absent until the session has been named — by the user, or by the daemon
 * from the first thing they said. Clients supply their own placeholder;
 * the daemon has no business picking a word in the user's language.
 */
title?: string, status: SessionStatus, modelId?: string, modeId?: string, createdAtMs: number, updatedAtMs: number, archived: boolean, };

/**
 * The machine-level settings a client may see and change.
 */
export type Settings = { providers: Array<ProviderInfo>, 
/**
 * Whether the daemon accepts connections from the local network.
 */
lanEnabled: boolean, };

/**
 * One entry in a session's timeline.
 *
 * `id` is assigned by the daemon, not the agent, so that deltas can address an
 * item regardless of whether the underlying agent has a concept of message ids.
 */
export type TimelineItem = { "type": "userMessage", id: string, text: string, attachments: Array<Attachment>, } | { "type": "assistantMessage", id: string, text: string, } | { "type": "reasoning", id: string, text: string, } | { "type": "toolCall", id: string, name: string, status: ToolStatus, detail: ToolCallDetail, } | { "type": "todo", id: string, items: Array<TodoEntry>, } | { "type": "compaction", id: string, reason: string, } | { "type": "error", id: string, message: string, };

export type TodoEntry = { text: string, status: TodoStatus, };

export type TodoStatus = "pending" | "inProgress" | "completed" | "cancelled";

/**
 * Which renderer the frontend should reach for.
 *
 * Adapters map their agent's tool names onto these variants. The mapping table
 * lives inside each adapter on purpose: a single global table would become a
 * coupling point between every adapter we ever add.
 */
export type ToolCallDetail = { "kind": "shell", command: string, output: string, exitCode?: number, } | { "kind": "read", path: string, content: string, truncated: boolean, } | { "kind": "edit", path: string, diff: string, } | { "kind": "write", path: string, content: string, } | { "kind": "search", query: string, matches: Array<SearchMatch>, } | { "kind": "fetch", url: string, summary: string, } | { "kind": "plan", markdown: string, } | { "kind": "subAgent", agent: string, prompt: string, items: Array<TimelineItem>, } | { "kind": "unknown", raw: JsonValue, };

export type ToolStatus = "pending" | "running" | "ok" | "error" | "canceled";

/**
 * How this client reached the daemon. Surfaced so the UI can show the user
 * which of the three paths in `architecture.md` §1 is in use.
 */
export type TransportKind = "loopback" | "lan" | "forwarded";

export type TurnError = { code: TurnErrorCode, 
/**
 * Already user-facing. §4.4 of `docs/testing.md` requires every failure
 * mode to surface something actionable rather than a blank screen.
 */
message: string, };

export type TurnErrorCode = "missingCredentials" | "rateLimited" | "upstream" | "timeout" | "agentCrashed" | "canceled" | "internal";

export type Usage = { inputTokens: number, outputTokens: number, cacheReadTokens: number, cacheWriteTokens: number, costUsd?: number, };

export type WorkspaceInfo = { id: string, name: string, root: string, isGitRepo: boolean, };
