// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServicePreviewDescriptor = { version: number, runId: string, name: string, routes: Array<ServicePreviewRoute>, media: ServicePreviewMedia | null, iceServers: Array<ServicePreviewIceServer>, dataPolicy: string, };

export type ServicePreviewIceServer = { urls: Array<string>, username: string | null, credential: string | null, };

export type ServicePreviewMedia = { offerPath: string, stopPath: string | null, microphone: string | null, };

export type ServicePreviewRoute = { prefix: string, websocket: boolean, };
