'use strict';
// Isolated design fixture: no daemon RPC, shell execution or real authorization.
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,action,extra='',cls='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const spaces=[{id:'camp',name:'微光营地',component:'PM',depth:0,machine:'studio'}, {id:'exec',name:'流程执行',component:'Executor',depth:1,machine:'studio'}, {id:'coder',name:'玩法与触屏开发',component:'Worker · Coder',depth:2,machine:'studio'}, {id:'review',name:'质量与体验验收',component:'Worker · Reviewer',depth:2,machine:'studio'}, {id:'wm',name:'工作流改进',component:'Worker · Executor',depth:2,machine:'studio'}, {id:'notes',name:'日常阅读笔记',component:'普通 Space',depth:0,machine:'studio'}, {id:'lab',name:'界面实验室',component:'普通 Space',depth:0,machine:'studio'}, {id:'travel',name:'旅行手记',component:'普通 Space',depth:0,machine:'laptop'}];
const seed=[{id:'pm',space:'camp',title:'让营地在夜晚也有故事',agent:'Codex',status:'idle'}, {id:'permission',space:'camp',title:'确认下一次项目调整',agent:'Cursor',status:'waiting'}, {id:'exec',space:'exec',title:'昼夜循环 · 执行记录',agent:'Executor',status:'running',readonly:true}, {id:'coder',space:'coder',title:'实现昼夜与萤火虫',agent:'Codex',status:'idle',readonly:true}, {id:'review',space:'review',title:'触屏验收失败 · 等待处理',agent:'Claude Code',status:'failed',readonly:true}, {id:'wm',space:'wm',title:'为这个项目设计管理页面',agent:'GeneHub Agent',status:'idle'}, {id:'notes',space:'notes',title:'整理本周的阅读笔记',agent:'Claude Code',status:'idle'}, {id:'question',space:'notes',title:'阅读清单按什么方式组织？',agent:'Claude Code',status:'waiting'}, {id:'lab',space:'lab',title:'调整移动端工具栏',agent:'Cursor',status:'idle'}, {id:'travel',space:'travel',title:'湖边环线 · 周末安排',agent:'GeneHub Agent',status:'idle'}];
const KEY='genehub-prototype-v4';
const fresh=()=>({section:'sessions',machine:'studio',sid:'pm',space:'camp',detail:true,filter:'all',sub:'sessions',tool:null,offline:false,drafts:{},extra:[],states:{},decisions:{},sent:{},expanded:true,archive:false,scroll:{}});
let s=fresh();try{const old=JSON.parse(localStorage.getItem(KEY));if(old&&old.version===4)s={...s,...old,offline:false};}catch{}
let selecting=false,selected=new Set(),dialog=null,focusBefore=null,search='',toastTimer;
const all=()=>[...seed,...s.extra].map(x=>({...x,...s.states[x.id]}));
const session=()=>all().find(x=>x.id===s.sid)||seed[0];
const space=id=>spaces.find(x=>x.id===id)||spaces[0];
const machineName=id=>id==='studio'?'工作室 Mac':'随行电脑';
const statusName=x=>({idle:'已结束',running:'进行中',waiting:'等待交互',failed:'执行失败',draft:'未发送草稿'})[x]||x;
const owned=()=>all().filter(x=>space(x.space).machine===s.machine);
const writable=x=>x&&!x.readonly&&!x.archived;
const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify({...s,version:4}));}catch{toast('浏览器未保存演示状态，本页仍可继续使用');}};
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',3200);}
const scrollKey=()=>`${s.section}/${s.sid}/${s.space}/${s.sub}/${s.tool||''}`;
function remember(){const el=$('.content');if(el)s.scroll[scrollKey()]=el.scrollTop;}
function navigate(fn){remember();fn();selecting=false;selected.clear();search='';render();}
function openSession(id){navigate(()=>{s.sid=id;s.space=session().space;s.machine=space(s.space).machine;s.section='sessions';s.detail=true;s.tool=null;});}
function appendDraft(id,text){s.drafts[id]=[s.drafts[id],text].filter(Boolean).join('\n\n');openSession(id);toast('已追加到草稿，请检查后发送');}
function messages(x){if(x.id==='notes'||x.id==='question')return [{who:'你',text:'帮我把本周的阅读笔记整理成可以继续讨论的提纲。'},{who:x.agent,text:'已经分成阅读线索、尚未解决的问题和下一步探索。交互提纲是普通 HTML 文件，任何空间都可以使用。'}];if(x.id==='wm')return [{who:'你',text:'我们不需要固定的项目看板。请按这个营地项目，做一个关注体验和决策的页面。'},{who:x.agent,text:'我会和你一起调整页面。布局与数据文件都在项目中；页面内容来自最近读取的记录，不会替代原始执行事实。'}];return [{who:'你',text:'保留营地的安静感，加入昼夜变化和可触摸的萤火虫。'},{who:x.agent,text:'实现和检查记录已经整理。项目页面由项目自己维护；你可以从这一回合 Fork，或选择部分消息交给另一个 Agent。'}];}
function rail(){return `<nav class="rail" aria-label="主导航"><div class="brand">◈</div>${[['sessions','◌','会话'],['spaces','▱','空间'],['discover','✧','发现'],['tools','☷','工具']].map(([id,g,t])=>btn(`<span class="glyph">${g}</span>${t}${id==='sessions'&&owned().some(x=>['waiting','failed'].includes(x.status)&&!x.archived)?'<i class="dot"></i>':''}`,'section',`data-id="${id}"`,s.section===id?'active':'')).join('')}<div class="foot">内容留在<br>你的机器上</div></nav>`;}
function row(x){return btn(`<strong>${esc(x.title)}${['waiting','failed'].includes(x.status)?'<i class="dot"></i>':''}</strong><small>${esc(space(x.space).name)} · ${esc(x.agent)}<br><span class="row-state">${statusName(x.status)}${x.readonly?' · 受管只读':''}${x.archived?' · 已归档':''}</span></small>`,'session',`data-id="${x.id}"`,s.sid===x.id&&s.section==='sessions'?'row active':'row');}
function catalog(){const title={sessions:'会话',spaces:'空间',discover:'发现',tools:'工具'}[s.section];let body='';
if(s.section==='sessions'){const rows=owned().filter(x=>s.archive?x.archived:!x.archived).filter(x=>x.status!=='draft').filter(x=>s.filter==='all'||['waiting','failed'].includes(x.status)).filter(x=>(x.title+space(x.space).name).includes(search));body=rows.map(row).join('')||'<p class="empty">这里暂时没有会话。</p>';}
if(s.section==='spaces')body=spaces.filter(x=>x.machine===s.machine&&(s.expanded||x.depth===0)).map(x=>`<div class="space-row" style="--depth:${x.depth}">${x.id==='camp'?btn(s.expanded?'⌄':'›','expand','','branch'):'<span style="width:26px"></span>'}${btn(`<strong>${esc(x.name)}</strong><small>${esc(x.component)}</small>`,'space',`data-id="${x.id}"`,s.space===x.id?'row active':'row')}</div>`).join('');
if(s.section==='discover')body='<div class="card"><span class="tag">预留能力</span><h3>让想法有来处</h3><p class="intro">这里将容纳来自各个空间的想法。当前还没有自动发现服务。</p>'+btn('查看建议体验示例','discover-demo')+'</div>';
if(s.section==='tools')body='<p class="intro" style="padding:12px">全局与机器级能力在这里。文件、变更和终端，请从所属空间进入。</p>'+btn('打开工具首页','tool-home','','row');
return `<aside class="catalog ${s.detail?'hide-mobile':''}"><div class="catalog-header">${btn(`◉ ${machineName(s.machine)} ⌄`,'machine','','machine')}<h1>${title}</h1>${s.section==='sessions'?`<input class="search" id="search" placeholder="搜索会话或空间" aria-label="搜索会话" value="${esc(search)}"><div class="filters">${btn('全部','filter','data-id="all"',s.filter==='all'?'active-filter':'')}${btn('需处理'+(owned().some(x=>['waiting','failed'].includes(x.status)&&!x.archived)?' ●':''),'filter','data-id="needs"',s.filter==='needs'?'active-filter':'')}${btn(s.archive?'返回未归档':'已归档','archives')}${btn('＋ 新会话','new')}</div>`:''}</div><div class="list">${body}</div></aside>`;}
function header(title,subtitle,actions=''){return `<header class="topline">${btn('‹','back','aria-label="返回列表"','back')}<div><div class="eyebrow">${esc(subtitle)}</div><h2>${esc(title)}</h2></div>${actions}</header>`;}
function sessionPage(){const x=session(),m=messages(x),data=s.sent[x.id]||[];let content='';
if(x.origin)content+=`<div class="scope">分支来源：${esc(x.origin)} · ${esc(x.forkMode||'历史重建')}${btn('查看来源','session',`data-id="${x.originId||'pm'}"`)}</div>`;
if(s.decisions[x.id])content+=`<div class="warning">${s.decisions[x.id]==='theme'?'已选择按主题，等待会话更新。':s.decisions[x.id]==='time'?'已选择按时间，等待会话更新。':s.decisions[x.id]==='approved'?'决定已接受，等待会话更新。':'本次请求已拒绝。'}<br>演示在此停留；没有后台回包，不能宣称已经开始执行。</div>`;
if(x.id==='exec'){content+=`<p class="intro">流程记录 · 机械执行的真实事件</p>${[['run.requested','已收到：实现昼夜循环',''],['node.assigned','实现节点已派发给 Coder','coder'],['node.completed','实现节点已完成','coder'],['node.assigned','验收节点已派发给 Reviewer','review']].map(([kind,text,id])=>`<article class="flow-line"><small>${kind}</small><p>${text}</p>${id?btn('查看工作会话','session',`data-id="${id}"`):''}</article>`).join('')}<div class="warning">当前 Run 尚未结束。失败详情以已有状态与证据为准，不补造历史事件。</div>`;}else{
content+=m.map((msg,i)=>`<article class="message ${i===0?'user':''} ${selected.has(i)?'selected':''}">${selecting?`<label><input type="checkbox" data-select="${i}" ${selected.has(i)?'checked':''} aria-label="选择第 ${i+1} 条消息"><span>`:''}<div class="author">${esc(msg.who)}</div><p>${esc(msg.text)}</p>${selecting?'</span></label>':''}</article>`).join('');
content+=`<details><summary>工具记录 · 读取项目文件 · 已完成</summary><pre class="terminal">read path="project/index.html"\n文件读取完成 · 内容已进入当前会话</pre></details><div class="actions"><span class="meta">本回合已结束 · 42 秒</span>${btn('用量详情','usage')}${btn('Fork','fork',s.offline?'disabled':'')}${btn('选择','select')}</div>`;
if(!selecting)content+=`<div class="file-card"><span>▧</span><div><b>${x.space==='notes'?'阅读提纲':'项目自定义页面'}</b><small>${x.space==='notes'?'reading/index.html':'project/index.html'} · 普通文件</small></div>${btn('预览','preview')}</div>`;
}
content+=data.map(text=>`<article class="message user"><div class="author">你 · 演示发送</div><p>${esc(text)}</p></article>`).join('');
let bottom='';if(selecting)bottom=`<div class="selectbar"><span>已选 ${selected.size} 条</span>${btn('复制','copy',selected.size?'':'disabled')}${btn('转发','forward',selected.size&&!s.offline?'':'disabled')}${btn('取消选择','cancel-select')}</div>`;
else if(x.status==='waiting')bottom=`<section class="approval"><h3>${x.id==='question'?'阅读清单如何组织？':'等待你确认项目调整'}</h3><p>${x.id==='question'?'这是普通结构化问题，进入会话后读取完整内容。':'请求已保存；等待期间不需要 Agent 进程保持在线。查看计划后再决定。'}</p><div class="actions">${btn('查看完整内容','plan')}${btn(x.id==='question'?'按主题':'拒绝','reject',s.offline?'disabled':'')}${btn(x.id==='question'?'按时间':'批准一次','approve',s.offline?'disabled':'','primary')}</div></section>`;
else if(writable(x))bottom=`<section class="composer"><textarea id="draft" aria-label="会话草稿" placeholder="继续讨论，或描述你希望怎样修改…">${esc(s.drafts[x.id]||'')}</textarea><div class="actions">${btn('＋ 附件','attachment')}${btn(`${esc(x.agent)} · 配置`,'config')}<span class="meta"></span>${x.status==='running'?btn('停止','stop',s.offline?'disabled':''):btn('发送','send',s.offline?'disabled':'','primary')}</div></section>`;
else bottom=`<div class="scope" style="margin:0;border-radius:0">${x.archived?'已归档；从会话菜单恢复后可继续。':'受管执行记录 · 当前会话只读，保留查看与可用的历史操作。'}</div>`;
return header(x.title,`${machineName(s.machine)} / ${space(x.space).name} · ${statusName(x.status)}`,btn('空间','space',`data-id="${x.space}"`)+btn('•••','session-menu','aria-label="会话菜单"'))+`<div class="content">${content}</div>`+bottom;}
function spacePage(){const w=space(s.space),tabs=[['sessions','会话'],['files','文件'],['changes','变更'],['terminal','终端']];let body=`<div class="scope">作用域固定：${machineName(w.machine)} / ${w.name}</div>`;
if(s.sub==='sessions')body+=`<div class="actions">${btn('＋ 新会话','new','','primary')}${btn('导入会话','import')}</div>${all().filter(x=>x.space===w.id&&!x.archived&&x.status!=='draft').map(row).join('')||'<p class="empty">这个空间还没有会话。</p>'}`;
if(s.sub==='files')body+=`<p class="intro">文件属于当前空间；不要求 PM、工作流或“产物”登记。</p><div class="file-card"><span>▧</span><div><b>${w.id==='notes'?'阅读提纲':'项目页面'}</b><small>${w.id==='notes'?'reading/index.html':'project/index.html'}</small></div>${btn('预览','preview-space')}</div><div class="file-card"><span>≡</span><div><b>页面数据</b><small>project/data.json · 项目自行定义格式</small></div>${btn('查看','data')}</div><div class="actions">${btn('新建 / 上传','file-actions')}${btn('文件管理操作','file-actions')}</div>`;
if(s.sub==='changes')body+=`<h3>工作区变更</h3><p class="intro">示例文件状态，复用现有 Git 面板。</p><div class="card">M　project/index.html<details><summary>查看差异</summary><pre class="terminal">- 默认模板标题\n+ 我们的营地观察室</pre></details></div>`;
if(s.sub==='terminal')body+=`<h3>终端</h3><div class="terminal">${machineName(w.machine)} / ${w.name}\n$ pwd\n~/Projects/${w.id}\n\n原型不执行命令。</div><p class="intro">正式版复用已有终端连接；切换会话不改变这个终端所属的空间。</p>`;
return header(w.name,`${machineName(w.machine)} / 空间 · ${w.component}`,btn('详情','space-details'))+`<nav class="subnav">${tabs.map(([id,t])=>btn(t,'sub',`data-id="${id}"`,s.sub===id?'active':'')).join('')}</nav><div class="content">${body}</div>`;}
const globalTools=[['computer','我的电脑','账号下的机器目录'],['processes','后台进程','指定机器的进程'],['devices','设备','连接与设备管理'],['settings','设置','工作台显示与偏好'],['feedback','产品反馈','宿主提供的反馈入口']];
function toolsPage(){if(!s.tool)return header('工具','全局能力与机器级工具')+`<div class="content"><p class="intro">工作区的文件、变更和终端放在空间里。这里的工具打开为页面。</p><div class="grid">${globalTools.map(([id,t,d])=>btn(`<b>${t}</b><small>${d}</small>`,'tool',`data-id="${id}"`,'tool-entry')).join('')}</div></div>`;
const t=globalTools.find(x=>x[0]===s.tool);let body='';if(s.tool==='computer'||s.tool==='devices')body=`<div class="grid">${['studio','laptop'].map(id=>`<div class="card"><b>${machineName(id)}</b><p class="intro">${id==='studio'?'工作室 · 在线':'随行 · 演示离线'}</p>${btn('查看该机器','switch-machine',`data-id="${id}"`)}</div>`).join('')}</div>`;
if(s.tool==='processes')body=`<div class="scope">机器：${machineName(s.machine)} · 无空间筛选</div><div class="terminal">daemon     工作台后台服务\nAgent      运行状态由实际进程回包决定</div><p class="intro">此处展示作用域与页面容器；不模拟终止真实进程。</p>`;
if(s.tool==='settings')body=`<div class="card"><h3>显示</h3><label>界面大小 <select id="density"><option>舒适</option><option>紧凑</option></select></label><p class="intro">设置页面独立于当前空间。</p></div>`;
if(s.tool==='feedback')body=`<div class="card"><h3>反馈 GeneHub 的使用问题</h3><p class="intro">产品反馈与项目文件反馈分开。本原型不会上传。</p><textarea id="product-feedback" aria-label="产品反馈" placeholder="发生了什么？" style="width:100%;min-height:120px"></textarea>${btn('保存演示反馈','product-feedback')}</div>`;
return header(t[1],'全局工具',btn('工具首页','tool-home'))+`<div class="content">${body}</div>`;}
function discovery(){return header('发现','为来自各个空间的想法预留位置')+`<div class="content"><div class="project-hero"><span class="tag">未来能力 · 尚未自动运行</span><h3>下一件值得试的事</h3><p>想法应带着来源、依据和可继续讨论的上下文。</p></div><div class="warning">下面是体验示例。当前没有跨空间扫描、自动生成、持久建议或去重服务；本轮不新增这些后台机制。</div><article class="card"><span class="tag">${machineName(s.machine)} / ${s.machine==='studio'?'日常阅读笔记':'旅行手记'}</span><h3>${s.machine==='studio'?'把三篇阅读笔记做成一次主题对谈':'给湖边行程留一个雨天备选'}</h3><p class="intro">依据：来源会话的已有讨论 · 示例时间 09:20</p><p>先和原 Agent 讨论是否有价值，再决定是否开展。</p>${btn('进入来源会话讨论','idea','','primary')} ${btn('暂不考虑','dismiss-idea')}</article><p class="intro">第一阶段正式落地可保留诚实空态；不要用定时器假装后台正在发现。</p></div>`;}
let previewContext=null;
function previewPage(){const c=previewContext,w=space(c.space);return header(c.notes?'阅读提纲':'营地观察室',`${machineName(w.machine)} / ${w.name} / ${c.notes?'reading':'project'}/index.html`,btn('返回','preview-back'))+`<div class="content"><div class="scope">公共文件预览 · ${c.origin?'来源会话已绑定':'从文件打开，未绑定反馈会话'}</div><div class="project-hero"><span>项目自行设计的 HTML</span><h3>${c.notes?'读过之后，留下问题。':'先照顾体验，再安排工作。'}</h3><p>这块内容由项目 Agent 与人共同维护。GeneHub 只提供预览容器。</p></div><div class="grid"><div class="card"><span class="tag">${c.notes?'阅读线索':'关注的体验'}</span><h3>${c.notes?'记忆与工具':'夜晚应当温柔'}</h3><p class="intro">页面没有固定流程列，也没有内置 PM 状态机。</p></div><div class="card"><span class="tag">项目文件中的摘要</span><h3>最近一次观察</h3><p class="intro">生成于 09:30 · 读取时间应由数据生产者写入；并非实时 Run 状态。</p></div></div><a href="project-page.html" target="_blank" rel="noopener">打开独立 HTML，体验两种项目布局 ↗</a><details><summary>文件读取与页面操作边界</summary><p class="intro">可用相对 fetch 读取项目 JSON。现有预览桥不提供 session.flow 或任意 RPC；页面里的勾选只属于页面本地状态。</p></details></div><section class="composer"><textarea id="preview-feedback" aria-label="文件反馈" placeholder="希望这个页面怎样改变？">${esc(c.feedback||'')}</textarea><div class="actions">${btn('截图 / 日志','capture')}<span class="meta">${c.origin?'反馈回来源会话草稿':'无来源：可复制反馈'}</span>${btn(c.origin?'带回草稿':'复制反馈','preview-submit',s.offline&&c.origin?'disabled':'','primary')}</div></section>`;}
function render(){persist();const body=previewContext?previewPage():s.section==='sessions'?sessionPage():s.section==='spaces'?spacePage():s.section==='tools'?toolsPage():discovery();$('#app').innerHTML=rail()+catalog()+`<main class="main ${!s.detail?'hide-mobile':''}">${s.offline?'<div class="banner">连接已断开 · 展示已有内容，执行操作不可用</div>':''}${body}</main>`;const el=$('.content');if(el)el.scrollTop=s.scroll[scrollKey()]||0;$('#offline').textContent=s.offline?'恢复连接':'模拟断线';}
function newDraft(targetSpace=s.space,agent='Codex',extra={}){const id='new-'+Date.now();s.extra.push({id,space:targetSpace,title:'新会话',agent,status:'draft',...extra});return id;}
function closeDialog(){dialog=null;$('#modal').innerHTML='';$('#app').inert=false;focusBefore?.focus?.();}
function showDialog(kind,title,body,footer=''){focusBefore=document.activeElement;dialog=kind;$('#app').inert=true;$('#modal').innerHTML=`<div class="modal-bg"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header><h3 id="dialog-title">${title}</h3>${btn('×','close-dialog','aria-label="关闭弹框"')}</header><div class="dialog-body">${body}</div>${footer?`<footer>${footer}</footer>`:''}</section></div>`;$('#modal button')?.focus();}
function picker(kind){const fork=kind==='fork',x=session();showDialog(kind,fork?'Fork 会话':'转发所选消息',`<p>来源：${esc(x.title)} · ${fork?'当前已结束回合':selected.size+' 条已选消息'}</p><label>目标机器<select id="target-machine"><option value="${s.machine}">${machineName(s.machine)} · 当前</option><option value="${s.machine==='studio'?'laptop':'studio'}">${machineName(s.machine==='studio'?'laptop':'studio')} · ${s.machine==='studio'?'离线':'在线'}</option></select></label><label>目标空间<select id="target-space">${spaces.filter(w=>w.machine===s.machine).map(w=>`<option value="${w.id}" ${w.id===x.space?'selected':''}>${w.name}</option>`).join('')}</select></label><label>目标 Agent<select id="target-agent">${['Codex','Cursor','Claude Code','GeneHub Agent'].map(a=>`<option ${a===x.agent?'selected':''}>${a}</option>`).join('')}</select></label>${!fork?`<label>目标会话<select id="target-session"><option value="new">新会话草稿</option>${owned().filter(writable).filter(y=>!y.archived&&y.status!=='waiting').map(y=>`<option value="${y.id}">${esc(y.title)}</option>`).join('')}</select></label><label>上下文预算<select><option>精要 8k</option><option selected>标准 16k</option><option>细节 32k</option><option>完整 64k</option></select></label><details><summary>内容预览</summary><p>${messages(x).filter((_,i)=>selected.has(i)).map(m=>esc(m.text)).join('<br>')}</p></details>`:''}<div id="target-note" class="warning"></div>`,btn('取消','close-dialog')+btn(fork?'创建分支':'放入目标草稿','confirm-target','','primary'));updateTarget();}
function updateTarget(){const machine=$('#target-machine').value,sp=$('#target-space'),x=session();if(![...sp.options].some(o=>space(o.value).machine===machine)){sp.innerHTML=spaces.filter(w=>w.machine===machine).map(w=>`<option value="${w.id}">${w.name}</option>`).join('');const target=$('#target-session');if(target)target.innerHTML='<option value="new">新会话</option>'+all().filter(y=>space(y.space).machine===machine&&writable(y)&&y.status!=='waiting').map(y=>`<option value="${y.id}">${esc(y.title)}</option>`).join('');}const offline=machine==='laptop';const native=machine===s.machine&&sp.value===x.space&&$('#target-agent').value===x.agent&&x.agent==='Codex'&&x.status==='idle';$('#target-note').textContent=offline?'目标机器离线，当前不可提交。':dialog==='fork'?(native?'演示：同机器、空间、Agent 且存在 checkpoint，使用原生 Fork。':'演示：从可用历史重建新会话，保留来源；不是复制原生工具进程。'):machine===s.machine?'本机转发放入目标草稿，由你检查后发送。':'跨机器由现有宿主 controller 投递，会直接送入目标会话；不是草稿。';const confirm=$('[data-action="confirm-target"]');confirm.disabled=offline||s.offline;confirm.textContent=dialog==='fork'?'创建分支':machine===s.machine?'放入目标草稿':'确认跨机投递';}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id,x=session();
if(a==='close-dialog')return closeDialog();
if(a==='section'){previewContext=null;navigate(()=>{s.section=id;s.detail=false;s.tool=null;});return;}
if(a==='session'){previewContext=null;return openSession(id);}
if(a==='back'){if(previewContext){previewContext=null;render();}else navigate(()=>{s.detail=false;});return;}
if(a==='space'){previewContext=null;navigate(()=>{s.space=id;s.section='spaces';s.detail=true;s.sub='sessions';});return;}
if(a==='expand'){s.expanded=!s.expanded;render();return;}
if(a==='filter'){navigate(()=>{s.filter=id;});return;}
if(a==='archives'){s.archive=!s.archive;render();return;}
if(a==='sub'){navigate(()=>{s.sub=id;});return;}
if(a==='tool'||a==='tool-home'){navigate(()=>{s.section='tools';s.tool=a==='tool'?id:null;s.detail=true;});return;}
if(a==='discover-demo'){s.detail=true;render();return;}
if(a==='machine')return showDialog('machine','选择机器',`${['studio','laptop'].map(m=>`<div class="card"><b>${machineName(m)}</b><p>${m==='studio'?'在线':'演示离线，可看已有列表'}</p>${btn('切换','switch-machine',`data-id="${m}"`)}</div>`).join('')}`);
if(a==='switch-machine'){closeDialog();previewContext=null;navigate(()=>{s.machine=id;s.sid=id==='studio'?'pm':'travel';s.space=id==='studio'?'camp':'travel';s.offline=id==='laptop';s.detail=false;s.tool=null;});return;}
if(a==='select'){selecting=true;selected=new Set([0,1]);render();return;}
if(a==='cancel-select'){selecting=false;selected.clear();render();return;}
if(a==='copy'){const text=messages(x).filter((_,i)=>selected.has(i)).map(m=>`${m.who}：${m.text}`).join('\n\n');try{await navigator.clipboard.writeText(text);toast(`已复制 ${selected.size} 条消息`);}catch{showDialog('copy','复制内容',`<textarea readonly>${esc(text)}</textarea><p>浏览器未允许自动复制，可手动选择文本。</p>`);}return;}
if(a==='fork'||a==='forward')return picker(a);
if(a==='confirm-target'){const kind=dialog,machine=$('#target-machine').value,targetSpace=$('#target-space').value,agent=$('#target-agent').value,native=$('#target-note').textContent.includes('使用原生');if(s.offline||machine==='laptop')return;let targetId;
if(kind==='fork'){targetId=newDraft(targetSpace,agent,{title:x.title+' · 分支',status:'idle',origin:x.title,originId:x.id,forkMode:native?'原生 Fork':'历史重建'});closeDialog();openSession(targetId);toast('演示分支已创建，未启动真实 Agent');}
else{const target=$('#target-session').value;targetId=target==='new'?newDraft(targetSpace,agent):target;const text='转发自「'+x.title+'」\n'+messages(x).filter((_,i)=>selected.has(i)).map(m=>m.who+'：'+m.text).join('\n');const cross=machine!==s.machine;closeDialog();if(cross){s.sent[targetId]=[...(s.sent[targetId]||[]),text];s.states[targetId]={...s.states[targetId],status:'idle',...(target==='new'?{title:'转发内容 · 演示投递'}:{})};openSession(targetId);toast('演示已跨机投递；真实版由宿主 controller 完成');}else appendDraft(targetId,text);}return;}
if(a==='usage')return showDialog('usage','回合用量',`<p>演示值：42 秒 · 3 次工具调用 · 1.2k 输出 tokens。</p><p>正式版沿用现有回合统计、缓存、工具用量与缺失值展示。</p>`);
if(a==='new')return showDialog('new','新会话',`<label>空间<select id="new-space">${spaces.filter(w=>w.machine===s.machine).map(w=>`<option value="${w.id}" ${w.id===s.space?'selected':''}>${w.name}</option>`).join('')}</select></label><label>Agent<select id="new-agent"><option>Codex</option><option>Cursor</option><option>Claude Code</option><option>GeneHub Agent</option></select></label><p>进入草稿，不发送就不加入已有会话列表。</p>`,btn('开始草稿','confirm-new','','primary'));
if(a==='confirm-new'){const target=newDraft($('#new-space').value,$('#new-agent').value);closeDialog();openSession(target);return;}
if(a==='send'){const text=(s.drafts[x.id]||'').trim();if(!text)return toast('先输入一些内容');s.sent[x.id]=[...(s.sent[x.id]||[]),text];s.drafts[x.id]='';if(x.status==='draft')s.states[x.id]={status:'idle',title:text.slice(0,25)};render();toast('演示消息已加入；没有调用 Agent');return;}
if(a==='session-menu')return showDialog('session-menu','会话操作',`<div class="grid">${btn('重命名','rename')}${btn(x.archived?'恢复会话':'归档会话','archive')}${btn('查看来源关系','lineage')}${btn('导入会话','import')}${btn('Agent 配置','config')}${btn('停止当前执行','stop',x.status==='running'&&!s.offline?'':'disabled')}</div><p>正式版按能力和会话状态启用；不以角色名称猜权限。</p>`);
if(a==='rename')return showDialog('rename','重命名会话',`<input id="rename" aria-label="会话名称" value="${esc(x.title)}">`,btn('保存','confirm-rename','','primary'));
if(a==='confirm-rename'){const title=$('#rename').value.trim();if(!title)return;s.states[x.id]={...s.states[x.id],title};closeDialog();render();return;}
if(a==='archive'){s.states[x.id]={...s.states[x.id],archived:!x.archived};closeDialog();render();return;}
if(a==='lineage')return showDialog('lineage','来源关系',`<p>${x.origin?'来源：'+esc(x.origin)+' · '+esc(x.forkMode):'当前是普通会话，没有分支来源。'}</p><p>正式版沿用 lineage、导入来源和已有历史引用。</p>`);
if(a==='config')return showDialog('config','Agent 运行配置',`<p>绑定的 Agent：${esc(x.agent)}</p><label>演示模型<select><option>使用当前 Agent 默认模型</option></select></label><label>权限模式<select><option>沿用当前模式</option></select></label><p>实际候选来自 Agent catalog / runtime capabilities。此处不虚构所有 Agent 都支持相同模型、模式或强度。</p>`,btn('返回会话','close-dialog'));
if(a==='import')return showDialog('import','导入已有会话',`<p>作用域：${esc(space(s.space).name)}</p><div class="card">原生 Agent 的会话候选将在此按需发现。<p class="intro">原型没有读取机器历史，不编造可导入候选。</p></div><p>复用 session.importList → session.import，候选票据由现有后端校验。</p>`);
if(a==='stop'){s.states[x.id]={...s.states[x.id],status:'idle'};closeDialog();render();toast('演示停止；正式版沿用 session.interrupt');return;}
if(a==='approve'||a==='reject'){s.states[x.id]={...s.states[x.id],status:'idle'};s.decisions[x.id]=x.id==='question'?(a==='approve'?'time':'theme'):(a==='approve'?'approved':'rejected');render();return;}
if(a==='plan')return showDialog('plan','完整请求',`<p>${x.id==='question'?'按主题或时间组织阅读清单。':'调整本项目的下一次执行计划；具体对象、revision、challenge 与影响范围由现有请求提供。'}</p><p>原型没有真实 challenge，不会签发 grant。读取完整请求沿用 session.get 与现有订阅。</p>`);
if(a==='preview'||a==='preview-space'){remember();previewContext={space:a==='preview'?x.space:s.space,origin:a==='preview'&&writable(x)?x.id:null,notes:(a==='preview'?x.space:s.space)==='notes',feedback:''};s.detail=true;render();return;}
if(a==='preview-back'){previewContext=null;render();return;}
if(a==='preview-submit'){const c=previewContext,text=(c.feedback||'').trim();if(!text)return toast('请先填写反馈');if(c.origin&&writable(all().find(y=>y.id===c.origin))){previewContext=null;appendDraft(c.origin,`关于 ${c.notes?'reading':'project'}/index.html：\n${text}`);}else{try{await navigator.clipboard.writeText(text);toast('反馈已复制，请选择会话后粘贴');}catch{showDialog('copy','复制反馈',`<textarea readonly>${esc(text)}</textarea>`);}}return;}
if(a==='capture')return showDialog('capture','预览采集',`<p>正式版复用现有截图、录制、日志和附件上传控件。</p><p>原型没有采集或上传；只有成功保存附件后，才能把真实附件引用放回草稿。没有来源会话时不能猜测目标。</p>`);
if(a==='attachment')return showDialog('attachment','添加附件',`<p>保留现有文件、图片与附件入口。本原型不读取本地文件、不上传。</p>`);
if(a==='space-details')return showDialog('space-details','空间详情',`<p>名称：${esc(space(s.space).name)}</p><p>机器：${machineName(s.machine)}</p><p>Component：${esc(space(s.space).component)}</p><p>当前 Parent 按真实 Pack：PM → Executor → Coder / Reviewer / WorkflowManager。</p><p>WorkflowManager 的归属纠正需要独立迁移，本次不伪造树关系。</p><details><summary>管理入口</summary><p>保留当前重命名、组件配置、移除等动作与 CAS / 授权检查；原型不执行这些动作。</p></details>`);
if(a==='data')return showDialog('data','project/data.json',`<pre class="terminal">{\n  "readAt": "09:30",\n  "observations": ["触屏需要再次验证"],\n  "source": "项目 Agent 最近读取的记录"\n}</pre><p>这是项目自定义数据，不增加 GeneHub 领域模型。</p>`);
if(a==='file-actions')return showDialog('files','空间文件操作',`<p>保留现有新建、上传、重命名、移动与删除。对象固定为 ${esc(space(s.space).name)}。</p><p>本页演示入口与作用域，不修改真实文件。</p>`);
if(a==='idea'){const target=s.machine==='studio'?'notes':'travel';appendDraft(target,s.machine==='studio'?'讨论发现页的示例想法：是否把三篇阅读笔记整理成主题对谈？':'讨论发现页的示例想法：给湖边行程补一个雨天备选。');return;}
if(a==='dismiss-idea'){b.closest('article').innerHTML='<p>本次示例已收起。</p><p class="intro">真实的忽略与去重机制未在本轮实现。</p>';return;}
if(a==='product-feedback'){toast($('#product-feedback').value.trim()?'演示反馈已保留在当前页面，未上传':'请先填写反馈');return;}
});
document.addEventListener('input',e=>{if(e.target.id==='draft'){s.drafts[s.sid]=e.target.value;persist();}if(e.target.id==='preview-feedback'&&previewContext)previewContext.feedback=e.target.value;if(e.target.id==='search'){search=e.target.value;const pos=e.target.selectionStart;render();$('#search').focus();$('#search').setSelectionRange(pos,pos);}});
document.addEventListener('change',e=>{if(e.target.dataset.select!==undefined){const i=Number(e.target.dataset.select);if(e.target.checked)selected.add(i);else selected.delete(i);render();}if(['target-machine','target-space','target-agent'].includes(e.target.id))updateTarget();if(e.target.id==='density'){$('#frame').style.fontSize=e.target.value==='紧凑'?'13px':'';toast('演示偏好已调整');}});
document.addEventListener('keydown',e=>{if(!dialog)return;if(e.key==='Escape'){e.preventDefault();closeDialog();}if(e.key==='Tab'){const nodes=[...$('#modal').querySelectorAll('button:not(:disabled),input,textarea,select,a[href]')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
$('#phone').onclick=()=>{$('#frame').classList.toggle('phone');$('#phone').textContent=$('#frame').classList.contains('phone')?'桌面视图':'手机视图';};
$('#offline').onclick=()=>{s.offline=!s.offline;render();};
$('#reset').onclick=()=>{closeDialog();s=fresh();previewContext=null;selecting=false;selected.clear();render();toast('演示状态已重置');};
render();
